// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Socigy.OpenSource.DB.SourceGenerator.Templates.CommandBuilders
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\CommandBuilders\PostgresqlUpdateCommandBuilder.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class PostgresqlUpdateCommandBuilder : PostgresqlUpdateCommandBuilderBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"using System;
using System.Text;
using System.Data.Common;
using System.Threading.Tasks;
using System.Linq.Expressions;
using System.Collections.Generic;
using Socigy.OpenSource.DB.Core;
using Socigy.OpenSource.DB.Core.CommandBuilders;
using Socigy.OpenSource.DB.Core.Interfaces;
using Socigy.OpenSource.DB.Core.Delegates;
using Socigy.OpenSource.DB.Core.Parsers;
using Socigy.OpenSource.DB.Core.Parsers.Postgresql;
using Npgsql;
using NpgsqlTypes;
using ");
            
            #line 20 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\CommandBuilders\PostgresqlUpdateCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n#nullable enable\r\n\r\nnamespace Socigy.OpenSource.DB.CommandBuilders.Postgresq" +
                    "l\r\n{\r\n    ");
            
            #line 26 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\CommandBuilders\PostgresqlUpdateCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CustomPreClass));
            
            #line default
            #line hidden
            this.Write("\r\n    public class Postgresql");
            
            #line 27 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\CommandBuilders\PostgresqlUpdateCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("UpdateCommandBuilder<T> : SqlCommandBuilder<Postgresql");
            
            #line 27 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\CommandBuilders\PostgresqlUpdateCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(@"UpdateCommandBuilder<T>>
        where T : IDbTable
    {
#if NET6_0_OR_GREATER
        protected System.Data.Common.DbBatch? _Batch;

        /// <summary>
        /// Specifies the batch to use for subsequent database operations.
        /// </summary>
        /// <remarks>If <paramref name=""batch""/> is <see langword=""null""/>, the method attempts to create a new
        /// batch from the current connection or transaction. The batch is used to group multiple database commands for
        /// execution as a single unit.</remarks>
        /// <param name=""batch"">The <see cref=""DbBatch""/> instance to associate with the operation, or <see langword=""null""/> to create a new
        /// batch from the current connection or transaction.</param>
        /// <returns>The current instance with the specified batch applied.</returns>
        /// <exception cref=""ArgumentNullException"">Thrown if <paramref name=""batch""/> is <see langword=""null""/> and neither a connection nor a transaction is
        /// specified.</exception>
        /// <exception cref=""InvalidOperationException"">Thrown if <paramref name=""batch""/> is <see langword=""null""/> and the provided transaction does not have an
        /// associated <see cref=""DbConnection""/>.</exception>
        public Postgresql");
            
            #line 46 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\CommandBuilders\PostgresqlUpdateCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("UpdateCommandBuilder<T> WithBatch(DbBatch? batch)\r\n        {\r\n            if (bat" +
                    "ch == null)\r\n            {\r\n                if (_Connection == null && _Transact" +
                    "ion == null)\r\n                    throw new ArgumentNullException(nameof(batch)," +
                    " \"If batch is null, either connection or transaction must be specified!\");\r\n\r\n  " +
                    "              _Batch = _Connection?.CreateBatch() ?? _Transaction!.Connection?.C" +
                    "reateBatch() ?? throw new InvalidOperationException(\"The provided transaction ha" +
                    "s no DbConnection from which a DbBatch could be created\");\r\n                _Bat" +
                    "ch.Transaction = _Transaction;\r\n            }\r\n            else\r\n               " +
                    " _Batch = batch;\r\n\r\n            return this;\r\n        }\r\n\r\n        /// <summary>" +
                    "\r\n        /// Adds a new command to the current batch operation.\r\n        /// </" +
                    "summary>\r\n        /// <remarks>This method should be called only after a batch h" +
                    "as been initialized using\r\n        /// WithBatch(). Attempting to add to a batch" +
                    " without initialization will result in an exception.</remarks>\r\n        /// <exc" +
                    "eption cref=\"InvalidOperationException\">Thrown if no batch has been provided. Ca" +
                    "ll WithBatch() before invoking this method.</exception>\r\n        public void Add" +
                    "ToBatch()\r\n        {\r\n            if (_Batch == null)\r\n                throw new" +
                    " InvalidOperationException(\"Cannot add to batch when no DbBatch was provided. Pl" +
                    "ease call WithBatch() first.\");\r\n\r\n            var batchCommand = _Batch.CreateB" +
                    "atchCommand();\r\n            _Batch.BatchCommands.Add(batchCommand);\r\n        }\r\n" +
                    "\r\n        /// <summary>\r\n        /// Adds a new command to the current database " +
                    "batch asynchronously.\r\n        /// </summary>\r\n        /// <remarks>This method " +
                    "should be called only after a batch has been initialized using\r\n        /// With" +
                    "Batch(). It is typically used to accumulate multiple commands for execution as a" +
                    " single batch\r\n        /// operation.</remarks>\r\n        /// <returns>A task tha" +
                    "t represents the asynchronous operation.</returns>\r\n        /// <exception cref=" +
                    "\"InvalidOperationException\">Thrown if no database batch has been provided. Call " +
                    "WithBatch() before invoking this method.</exception>\r\n        public async Task " +
                    "AddToBatchAsync()\r\n        {\r\n            if (_Batch == null)\r\n                t" +
                    "hrow new InvalidOperationException(\"Cannot add to batch when no DbBatch was prov" +
                    "ided. Please call WithBatch() first.\");\r\n\r\n            var batchCommand = _Batch" +
                    ".CreateBatchCommand();\r\n            _Batch.BatchCommands.Add(batchCommand);\r\n   " +
                    "     }\r\n#endif\r\n\r\n        private readonly T _TableRow;\r\n        private Express" +
                    "ion<Func<T, bool>> _WhereClause;\r\n\r\n        private bool AllFieldsSet = false;\r\n" +
                    "        private Expression<Func<T, object?[]>> _UpdateClause;\r\n        private E" +
                    "xpression<Func<T, object?[]>> _UpdateExceptClause;\r\n\r\n        public Postgresql");
            
            #line 102 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\CommandBuilders\PostgresqlUpdateCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("UpdateCommandBuilder(T rowInstance)\r\n        {\r\n            _TableRow = rowInstan" +
                    "ce;\r\n        }\r\n\r\n        public Postgresql");
            
            #line 107 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\CommandBuilders\PostgresqlUpdateCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(@"UpdateCommandBuilder<T> Where(Expression<Func<T, bool>> where)
        {
            _WhereClause = where;
            return this;
        }

        private ISqlVisitor GetWhereVisitor(ParameterExpression param, GetColumnName getColName, DbCommand command)
        {
            return new PostgresqlWhereVisitor(param, getColName, command);
        }
        private ISqlVisitor GetUpdateSetVisitor(ParameterExpression param, GetColumnName getColName, DbCommand command)
        {
            return new PostgresqlUpdateVisitor(param, getColName, command, _TableRow);
        }

        /// <summary>
        /// Configures the builder to include all fields of the entity in the update operation.
        /// </summary>
        /// <remarks>After calling this method, all fields of the entity type <typeparamref name=""T""/>
        /// will be included in the generated update command, overriding any previous field selections. This method is
        /// typically used in fluent configuration scenarios.</remarks>
        /// <returns>The current <see cref=""Postgresql");
            
            #line 128 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\CommandBuilders\PostgresqlUpdateCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("UpdateCommandBuilder{T}\"/> instance for method chaining.</returns>\r\n        publi" +
                    "c Postgresql");
            
            #line 129 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\CommandBuilders\PostgresqlUpdateCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(@"UpdateCommandBuilder<T> WithAllFields()
        {
            if (_UpdateClause != null)
                throw new InvalidOperationException(""Cannot combine WithAllFields() with WithFields()."");

            AllFieldsSet = true;
            return this;
        }

        /// <summary>
        /// Specifies the fields to include in the update operation using a selection expression.
        /// </summary>
        /// <remarks>This method cannot be used in combination with <see cref=""WithAllFields""/>. Call this
        /// method to limit the update to specific fields rather than updating all fields.</remarks>
        /// <param name=""select"">An expression that selects the fields of the T entity to be updated. The expression should return an
        /// array of properties to include in the update.</param>
        /// <returns>The current <see cref=""Postgresql");
            
            #line 145 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\CommandBuilders\PostgresqlUpdateCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(@"UpdateCommandBuilder{T}""/> instance with the specified fields configured.</returns>
        /// <exception cref=""InvalidOperationException"">Thrown if all fields have already been specified using <see cref=""WithAllFields""/>.</exception>
        public Postgresql");
            
            #line 147 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\CommandBuilders\PostgresqlUpdateCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(@"UpdateCommandBuilder<T> WithFields(Expression<Func<T, object?[]>> select)
        {
            if (AllFieldsSet)
                throw new InvalidOperationException(""Cannot specify individual fields when WithAllFields() is set."");

            if (_UpdateExceptClause != null)
                throw new InvalidOperationException(""Cannot combine WithFields() with ExceptFields()."");

            _UpdateClause = select;
            return this;
        }

        /// <summary>
        /// Excludes the specified fields from being updated in the command builder.
        /// </summary>
        /// <remarks>Use this method to prevent certain fields from being included in the generated update
        /// statement. This is useful when you want to update only a subset of an entity's properties.</remarks>
        /// <param name=""except"">An expression that selects the properties of the <see cref=""T""/> entity to exclude from the update
        /// operation. The expression should return an array of properties to be omitted.</param>
        /// <returns>The current <see cref=""Postgresql");
            
            #line 166 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\CommandBuilders\PostgresqlUpdateCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("UpdateCommandBuilder{T}\"/> instance with the specified fields excluded from updat" +
                    "es.</returns>\r\n        public Postgresql");
            
            #line 167 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\CommandBuilders\PostgresqlUpdateCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(@"UpdateCommandBuilder<T> ExceptFields(Expression<Func<T, object?[]>> except)
        {
            if (_UpdateClause != null)
                throw new InvalidOperationException(""Cannot combine ExceptFields() with WithFields()."");

            _UpdateExceptClause = except;
            return this;
        }

        private HashSet<string>? BuildExcludedDbColumns(NpgsqlCommand command)
        {
            if (_UpdateExceptClause == null)
                return null;

            var extractor = new PostgresqlUpdateVisitor(
                _UpdateExceptClause.Parameters[0],
                ");
            
            #line 183 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\CommandBuilders\PostgresqlUpdateCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(@".GetColumnDbName,
                command);

            // Extracted values are C# member names.
            var extractedMemberNames = extractor.ExtractColumnNames(_UpdateExceptClause);

            // Convert to DB column names so they match _TableRow.GetColumns() keys.
            var excludedDbColumns = new HashSet<string>(StringComparer.Ordinal);
            foreach (var memberName in extractedMemberNames)
            {
                var dbName = ");
            
            #line 193 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\CommandBuilders\PostgresqlUpdateCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(@".GetColumnDbName(memberName);
                if (!string.IsNullOrEmpty(dbName))
                    excludedDbColumns.Add(dbName);
            }

            return excludedDbColumns;
        }

        private string BuildSetClause(NpgsqlCommand command)
        {
            var updateVisitor = GetUpdateSetVisitor(
                _UpdateClause?.Parameters[0]
                    ?? _UpdateExceptClause?.Parameters[0]
                    ?? Expression.Parameter(typeof(T), ""x""),
                ");
            
            #line 207 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\CommandBuilders\PostgresqlUpdateCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(".GetColumnDbName,\r\n                command);\r\n\r\n            // IMPORTANT: only us" +
                    "e explicit WithFields() when not in AllFields mode\r\n            if (_UpdateClaus" +
                    "e != null && !AllFieldsSet)\r\n                return updateVisitor.Parse(_UpdateC" +
                    "lause);\r\n\r\n            HashSet<string>? excludedDbColumns = BuildExcludedDbColum" +
                    "ns(command);\r\n\r\n            Dictionary<string, ColumnInfo> allColumns = _TableRo" +
                    "w.GetColumns();\r\n            var sb = new StringBuilder();\r\n            bool fir" +
                    "st = true;\r\n\r\n            foreach (var kv in allColumns)\r\n            {\r\n       " +
                    "         var dbColumnName = kv.Key;\r\n                var info = kv.Value;\r\n\r\n   " +
                    "             if (excludedDbColumns != null && excludedDbColumns.Contains(dbColum" +
                    "nName))\r\n                    continue;\r\n\r\n                if (!first)\r\n         " +
                    "           sb.Append(\", \");\r\n\r\n                first = false;\r\n\r\n               " +
                    " string paramName = $\"@p{command.Parameters.Count}\";\r\n\r\n                var p = " +
                    "command.CreateParameter()\r\n                    ?? throw new InvalidOperationExce" +
                    "ption(\"Expected NpgsqlCommand.\");\r\n\r\n                object? dbValue = Normalize" +
                    "DbValue(info.Type, info.Value);\r\n\r\n                p.ParameterName = paramName;\r" +
                    "\n                p.Value = dbValue ?? DBNull.Value;\r\n\r\n                if (dbVal" +
                    "ue == null || dbValue == DBNull.Value || IsEnumType(info.Type))\r\n               " +
                    "     p.NpgsqlDbType = GetDbType(info.Type);\r\n\r\n                command.Parameter" +
                    "s.Add(p);\r\n                sb.Append($\"\\\"{dbColumnName}\\\" = {paramName}\");\r\n    " +
                    "        }\r\n\r\n            return sb.ToString();\r\n        }\r\n\r\n        /// <summar" +
                    "y>\r\n        /// Executes the update command asynchronously against the database " +
                    "connection and returns the number of rows\r\n        /// affected.\r\n        /// </" +
                    "summary>\r\n        /// <remarks>If the database connection is not already open, t" +
                    "his method opens it before executing\r\n        /// the command. The update is per" +
                    "formed using either the specified WHERE clause or the primary key columns of\r\n  " +
                    "      /// the table row.</remarks>\r\n        /// <returns>A task that represents " +
                    "the asynchronous operation. The task result contains the number of rows affected" +
                    " by\r\n        /// the update command. Returns 0 if the command could not be creat" +
                    "ed.</returns>\r\n        /// <exception cref=\"InvalidOperationException\">Thrown if" +
                    " a DbBatch was provided, or if no DbConnection is available.</exception>\r\n      " +
                    "  public async Task<int> ExecuteAsync()\r\n        {\r\n#if NET6_0_OR_GREATER\r\n     " +
                    "       if (_Batch != null)\r\n                throw new InvalidOperationException(" +
                    "\"Cannot execute command when DbBatch was provided.\");\r\n#endif\r\n\r\n            if " +
                    "(_Connection == null)\r\n                throw new InvalidOperationException(\"No D" +
                    "bConnection provided.\");\r\n\r\n            if (_Connection.State != System.Data.Con" +
                    "nectionState.Open)\r\n                await _Connection.OpenAsync();\r\n\r\n          " +
                    "  await using var command = _Connection.CreateCommand() as NpgsqlCommand;\r\n     " +
                    "       if (command == null) return 0;\r\n\r\n            if (_Transaction != null)\r\n" +
                    "                command.Transaction = _Transaction as NpgsqlTransaction;\r\n\r\n    " +
                    "        string? where = null;\r\n            if (_WhereClause != null)\r\n          " +
                    "      where = GetWhereVisitor(_WhereClause.Parameters[0], ");
            
            #line 284 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\CommandBuilders\PostgresqlUpdateCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(".GetColumnDbName, command).Parse(_WhereClause);\r\n            else\r\n            {\r" +
                    "\n                var predicates = new List<string>();\r\n\r\n                Diction" +
                    "ary<string, ColumnInfo> columns = _TableRow.GetPrimaryColumns();\r\n              " +
                    "  foreach (var col in columns)\r\n                {\r\n                    string pa" +
                    "ramName = $\"@p{command.Parameters.Count}\";\r\n                    string colName =" +
                    " col.Key;\r\n\r\n                    object? dbValue = NormalizeDbValue(col.Value.Ty" +
                    "pe, col.Value.Value);\r\n\r\n                    var param = new NpgsqlParameter(par" +
                    "amName, dbValue ?? DBNull.Value);\r\n\r\n                    if (dbValue == null || " +
                    "dbValue == DBNull.Value || IsEnumType(col.Value.Type))\r\n                        " +
                    "param.NpgsqlDbType = GetDbType(col.Value.Type);\r\n\r\n                    command.P" +
                    "arameters.Add(param);\r\n                    predicates.Add($\"{colName} = {paramNa" +
                    "me}\");\r\n                }\r\n\r\n                where = \"WHERE \" + string.Join(\" AN" +
                    "D \", predicates);\r\n            }\r\n\r\n            command.CommandText = $@\"\r\n     " +
                    "   UPDATE \"\"{_TableRow.GetTableName()}\"\"\r\n        SET {BuildSetClause(command)}\r" +
                    "\n        {where}\";\r\n\r\n            int rowsAffected = await command.ExecuteNonQue" +
                    "ryAsync();\r\n            return rowsAffected;\r\n        }\r\n\r\n        public Npgsql" +
                    "DbType GetDbType(Type type)\r\n        {\r\n            type = Nullable.GetUnderlyin" +
                    "gType(type) ?? type;\r\n\r\n            if (type.IsEnum)\r\n                type = Enu" +
                    "m.GetUnderlyingType(type);\r\n\r\n            return type switch\r\n            {\r\n   " +
                    "             Type t when t == typeof(short) => NpgsqlDbType.Smallint,\r\n         " +
                    "       Type t when t == typeof(byte) => NpgsqlDbType.Smallint,\r\n                " +
                    "Type t when t == typeof(sbyte) => NpgsqlDbType.Smallint,\r\n\r\n                Type" +
                    " t when t == typeof(int) => NpgsqlDbType.Integer,\r\n                Type t when t" +
                    " == typeof(ushort) => NpgsqlDbType.Integer,\r\n\r\n                Type t when t == " +
                    "typeof(long) => NpgsqlDbType.Bigint,\r\n                Type t when t == typeof(ui" +
                    "nt) => NpgsqlDbType.Bigint,\r\n\r\n                Type t when t == typeof(ulong) =>" +
                    " NpgsqlDbType.Numeric,\r\n\r\n                Type t when t == typeof(string) => Npg" +
                    "sqlDbType.Text,\r\n                Type t when t == typeof(bool) => NpgsqlDbType.B" +
                    "oolean,\r\n                Type t when t == typeof(DateTime) => NpgsqlDbType.Times" +
                    "tamp,\r\n                Type t when t == typeof(float) => NpgsqlDbType.Real,\r\n   " +
                    "             Type t when t == typeof(double) => NpgsqlDbType.Double,\r\n          " +
                    "      Type t when t == typeof(decimal) => NpgsqlDbType.Numeric,\r\n               " +
                    " Type t when t == typeof(Guid) => NpgsqlDbType.Uuid,\r\n                Type t whe" +
                    "n t == typeof(byte[]) => NpgsqlDbType.Bytea,\r\n                Type t when t == t" +
                    "ypeof(char) => NpgsqlDbType.Char,\r\n                _ => NpgsqlDbType.Text\r\n     " +
                    "       };\r\n        }\r\n\r\n        private static bool IsEnumType(Type type)\r\n     " +
                    "   {\r\n            type = Nullable.GetUnderlyingType(type) ?? type;\r\n            " +
                    "return type.IsEnum;\r\n        }\r\n\r\n        private static object? NormalizeDbValu" +
                    "e(Type type, object? value)\r\n        {\r\n            if (value == null || value =" +
                    "= DBNull.Value)\r\n                return value;\r\n\r\n            var actualType = N" +
                    "ullable.GetUnderlyingType(type) ?? type;\r\n            if (!actualType.IsEnum)\r\n " +
                    "               return value;\r\n\r\n            var enumUnderlyingType = Enum.GetUnd" +
                    "erlyingType(actualType);\r\n            return Convert.ChangeType(value, enumUnder" +
                    "lyingType);\r\n        }\r\n    }\r\n    ");
            
            #line 371 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\CommandBuilders\PostgresqlUpdateCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CustomPostClass));
            
            #line default
            #line hidden
            this.Write("\r\n}\r\n\r\n#nullable disable\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 376 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\CommandBuilders\PostgresqlUpdateCommandBuilder.tt"

	public string ClassName { get; set; }
	public string Namespace { get; set; }

    public string CustomPreClass { get; set; } = "";
    public string CustomPostClass { get; set; } = "";

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public class PostgresqlUpdateCommandBuilderBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
