//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Socigy.OpenSource.DB.SourceGenerator.Templates.CommandBuilders {
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    
    public partial class PostgresqlUpdateCommandBuilder : PostgresqlUpdateCommandBuilderBase {
        
        
        #line 423 "PostgresqlUpdateCommandBuilder.tt"

	public string ClassName { get; set; }
	public string Namespace { get; set; }

    public string CustomPreClass { get; set; } = "";
    public string CustomPostClass { get; set; } = "";

        #line default
        #line hidden
        
        
        public virtual string TransformText() {
            this.GenerationEnvironment = null;
            
            #line 6 "PostgresqlUpdateCommandBuilder.tt"
            this.Write(@"#pragma warning disable
using System;
using System.Text;
using System.Data.Common;
using System.Threading.Tasks;
using System.Linq.Expressions;
using System.Collections.Generic;
using Socigy.OpenSource.DB.Core;
using Socigy.OpenSource.DB.Core.CommandBuilders;
using Socigy.OpenSource.DB.Core.Interfaces;
using Socigy.OpenSource.DB.Core.Delegates;
using Socigy.OpenSource.DB.Core.Parsers;
using Socigy.OpenSource.DB.Core.Parsers.Postgresql;
using Npgsql;
using NpgsqlTypes;
using ");
            
            #line default
            #line hidden
            
            #line 21 "PostgresqlUpdateCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Namespace ));
            
            #line default
            #line hidden
            
            #line 21 "PostgresqlUpdateCommandBuilder.tt"
            this.Write(";\n\n#nullable enable\n\nnamespace Socigy.OpenSource.DB.CommandBuilders.Postgresql\n{\n" +
                    "    ");
            
            #line default
            #line hidden
            
            #line 27 "PostgresqlUpdateCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( CustomPreClass ));
            
            #line default
            #line hidden
            
            #line 27 "PostgresqlUpdateCommandBuilder.tt"
            this.Write("\n    public class Postgresql");
            
            #line default
            #line hidden
            
            #line 28 "PostgresqlUpdateCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( ClassName ));
            
            #line default
            #line hidden
            
            #line 28 "PostgresqlUpdateCommandBuilder.tt"
            this.Write("UpdateCommandBuilder<T> : SqlCommandBuilder<Postgresql");
            
            #line default
            #line hidden
            
            #line 28 "PostgresqlUpdateCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( ClassName ));
            
            #line default
            #line hidden
            
            #line 28 "PostgresqlUpdateCommandBuilder.tt"
            this.Write(@"UpdateCommandBuilder<T>>
        where T : IDbTable
    {
#if NET6_0_OR_GREATER
        protected System.Data.Common.DbBatch? _Batch;

        /// <summary>
        /// Specifies the batch to use for subsequent database operations.
        /// </summary>
        /// <remarks>If <paramref name=""batch""/> is <see langword=""null""/>, the method attempts to create a new
        /// batch from the current connection or transaction. The batch is used to group multiple database commands for
        /// execution as a single unit.</remarks>
        /// <param name=""batch"">The <see cref=""DbBatch""/> instance to associate with the operation, or <see langword=""null""/> to create a new
        /// batch from the current connection or transaction.</param>
        /// <returns>The current instance with the specified batch applied.</returns>
        /// <exception cref=""ArgumentNullException"">Thrown if <paramref name=""batch""/> is <see langword=""null""/> and neither a connection nor a transaction is
        /// specified.</exception>
        /// <exception cref=""InvalidOperationException"">Thrown if <paramref name=""batch""/> is <see langword=""null""/> and the provided transaction does not have an
        /// associated <see cref=""DbConnection""/>.</exception>
        public Postgresql");
            
            #line default
            #line hidden
            
            #line 47 "PostgresqlUpdateCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( ClassName ));
            
            #line default
            #line hidden
            
            #line 47 "PostgresqlUpdateCommandBuilder.tt"
            this.Write("UpdateCommandBuilder<T> WithBatch(DbBatch? batch)\n        {\n            if (batch" +
                    " == null)\n            {\n                if (_Connection == null && _Transaction " +
                    "== null)\n                    throw new ArgumentNullException(nameof(batch), \"If " +
                    "batch is null, either connection or transaction must be specified!\");\n\n         " +
                    "       _Batch = _Connection?.CreateBatch() ?? _Transaction!.Connection?.CreateBa" +
                    "tch() ?? throw new InvalidOperationException(\"The provided transaction has no Db" +
                    "Connection from which a DbBatch could be created\");\n                _Batch.Trans" +
                    "action = _Transaction;\n            }\n            else\n                _Batch = b" +
                    "atch;\n\n            return this;\n        }\n\n        /// <summary>\n        /// Add" +
                    "s a new command to the current batch operation.\n        /// </summary>\n        /" +
                    "// <remarks>This method should be called only after a batch has been initialized" +
                    " using\n        /// WithBatch(). Attempting to add to a batch without initializat" +
                    "ion will result in an exception.</remarks>\n        /// <exception cref=\"InvalidO" +
                    "perationException\">Thrown if no batch has been provided. Call WithBatch() before" +
                    " invoking this method.</exception>\n        public void AddToBatch()\n        {\n  " +
                    "          if (_Batch == null)\n                throw new InvalidOperationExceptio" +
                    "n(\"Cannot add to batch when no DbBatch was provided. Please call WithBatch() fir" +
                    "st.\");\n\n            var batchCommand = _Batch.CreateBatchCommand();\n            " +
                    "_Batch.BatchCommands.Add(batchCommand);\n        }\n\n        /// <summary>\n       " +
                    " /// Adds a new command to the current database batch asynchronously.\n        //" +
                    "/ </summary>\n        /// <remarks>This method should be called only after a batc" +
                    "h has been initialized using\n        /// WithBatch(). It is typically used to ac" +
                    "cumulate multiple commands for execution as a single batch\n        /// operation" +
                    ".</remarks>\n        /// <returns>A task that represents the asynchronous operati" +
                    "on.</returns>\n        /// <exception cref=\"InvalidOperationException\">Thrown if " +
                    "no database batch has been provided. Call WithBatch() before invoking this metho" +
                    "d.</exception>\n        public async Task AddToBatchAsync()\n        {\n           " +
                    " if (_Batch == null)\n                throw new InvalidOperationException(\"Cannot" +
                    " add to batch when no DbBatch was provided. Please call WithBatch() first.\");\n\n " +
                    "           var batchCommand = _Batch.CreateBatchCommand();\n            _Batch.Ba" +
                    "tchCommands.Add(batchCommand);\n        }\n#endif\n\n        private readonly T _Tab" +
                    "leRow;\n        private Expression<Func<T, bool>> _WhereClause;\n\n        private " +
                    "bool AllFieldsSet = false;\n        private Expression<Func<T, object?[]>> _Updat" +
                    "eClause;\n        private Expression<Func<T, object?[]>> _UpdateExceptClause;\n\n  " +
                    "      public Postgresql");
            
            #line default
            #line hidden
            
            #line 103 "PostgresqlUpdateCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( ClassName ));
            
            #line default
            #line hidden
            
            #line 103 "PostgresqlUpdateCommandBuilder.tt"
            this.Write("UpdateCommandBuilder(T rowInstance)\n        {\n            _TableRow = rowInstance" +
                    ";\n        }\n\n        public Postgresql");
            
            #line default
            #line hidden
            
            #line 108 "PostgresqlUpdateCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( ClassName ));
            
            #line default
            #line hidden
            
            #line 108 "PostgresqlUpdateCommandBuilder.tt"
            this.Write(@"UpdateCommandBuilder<T> Where(Expression<Func<T, bool>> where)
        {
            _WhereClause = where;
            return this;
        }

        private ISqlVisitor GetWhereVisitor(ParameterExpression param, GetColumnName getColName, DbCommand command)
        {
            return new PostgresqlWhereVisitor(param, getColName, command);
        }
        private ISqlVisitor GetUpdateSetVisitor(ParameterExpression param, GetColumnName getColName, DbCommand command)
        {
            return new PostgresqlUpdateVisitor(param, getColName, command, _TableRow);
        }

        /// <summary>
        /// Configures the builder to include all fields of the entity in the update operation.
        /// </summary>
        /// <remarks>After calling this method, all fields of the entity type <typeparamref name=""T""/>
        /// will be included in the generated update command, overriding any previous field selections. This method is
        /// typically used in fluent configuration scenarios.</remarks>
        /// <returns>The current <see cref=""Postgresql");
            
            #line default
            #line hidden
            
            #line 129 "PostgresqlUpdateCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( ClassName ));
            
            #line default
            #line hidden
            
            #line 129 "PostgresqlUpdateCommandBuilder.tt"
            this.Write("UpdateCommandBuilder{T}\"/> instance for method chaining.</returns>\n        public" +
                    " Postgresql");
            
            #line default
            #line hidden
            
            #line 130 "PostgresqlUpdateCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( ClassName ));
            
            #line default
            #line hidden
            
            #line 130 "PostgresqlUpdateCommandBuilder.tt"
            this.Write(@"UpdateCommandBuilder<T> WithAllFields()
        {
            if (_UpdateClause != null)
                throw new InvalidOperationException(""Cannot combine WithAllFields() with WithFields()."");

            AllFieldsSet = true;
            return this;
        }

        /// <summary>
        /// Specifies the fields to include in the update operation using a selection expression.
        /// </summary>
        /// <remarks>This method cannot be used in combination with <see cref=""WithAllFields""/>. Call this
        /// method to limit the update to specific fields rather than updating all fields.</remarks>
        /// <param name=""select"">An expression that selects the fields of the T entity to be updated. The expression should return an
        /// array of properties to include in the update.</param>
        /// <returns>The current <see cref=""Postgresql");
            
            #line default
            #line hidden
            
            #line 146 "PostgresqlUpdateCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( ClassName ));
            
            #line default
            #line hidden
            
            #line 146 "PostgresqlUpdateCommandBuilder.tt"
            this.Write(@"UpdateCommandBuilder{T}""/> instance with the specified fields configured.</returns>
        /// <exception cref=""InvalidOperationException"">Thrown if all fields have already been specified using <see cref=""WithAllFields""/>.</exception>
        public Postgresql");
            
            #line default
            #line hidden
            
            #line 148 "PostgresqlUpdateCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( ClassName ));
            
            #line default
            #line hidden
            
            #line 148 "PostgresqlUpdateCommandBuilder.tt"
            this.Write(@"UpdateCommandBuilder<T> WithFields(Expression<Func<T, object?[]>> select)
        {
            if (AllFieldsSet)
                throw new InvalidOperationException(""Cannot specify individual fields when WithAllFields() is set."");

            if (_UpdateExceptClause != null)
                throw new InvalidOperationException(""Cannot combine WithFields() with ExceptFields()."");

            _UpdateClause = select;
            return this;
        }

        /// <summary>
        /// Excludes the specified fields from being updated in the command builder.
        /// </summary>
        /// <remarks>Use this method to prevent certain fields from being included in the generated update
        /// statement. This is useful when you want to update only a subset of an entity's properties.</remarks>
        /// <param name=""except"">An expression that selects the properties of the <see cref=""T""/> entity to exclude from the update
        /// operation. The expression should return an array of properties to be omitted.</param>
        /// <returns>The current <see cref=""Postgresql");
            
            #line default
            #line hidden
            
            #line 167 "PostgresqlUpdateCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( ClassName ));
            
            #line default
            #line hidden
            
            #line 167 "PostgresqlUpdateCommandBuilder.tt"
            this.Write("UpdateCommandBuilder{T}\"/> instance with the specified fields excluded from updat" +
                    "es.</returns>\n        public Postgresql");
            
            #line default
            #line hidden
            
            #line 168 "PostgresqlUpdateCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( ClassName ));
            
            #line default
            #line hidden
            
            #line 168 "PostgresqlUpdateCommandBuilder.tt"
            this.Write(@"UpdateCommandBuilder<T> ExceptFields(Expression<Func<T, object?[]>> except)
        {
            if (_UpdateClause != null)
                throw new InvalidOperationException(""Cannot combine ExceptFields() with WithFields()."");

            _UpdateExceptClause = except;
            return this;
        }

        private HashSet<string>? BuildExcludedDbColumns(NpgsqlCommand command)
        {
            if (_UpdateExceptClause == null)
                return null;

            var extractor = new PostgresqlUpdateVisitor(
                _UpdateExceptClause.Parameters[0],
                ");
            
            #line default
            #line hidden
            
            #line 184 "PostgresqlUpdateCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( ClassName ));
            
            #line default
            #line hidden
            
            #line 184 "PostgresqlUpdateCommandBuilder.tt"
            this.Write(@".GetColumnDbName,
                command);

            // Extracted values are C# member names.
            var extractedMemberNames = extractor.ExtractColumnNames(_UpdateExceptClause);

            // Convert to DB column names so they match _TableRow.GetColumns() keys.
            var excludedDbColumns = new HashSet<string>(StringComparer.Ordinal);
            foreach (var memberName in extractedMemberNames)
            {
                var dbName = ");
            
            #line default
            #line hidden
            
            #line 194 "PostgresqlUpdateCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( ClassName ));
            
            #line default
            #line hidden
            
            #line 194 "PostgresqlUpdateCommandBuilder.tt"
            this.Write(@".GetColumnDbName(memberName);
                if (!string.IsNullOrEmpty(dbName))
                    excludedDbColumns.Add(dbName);
            }

            return excludedDbColumns;
        }

        private string BuildSetClause(NpgsqlCommand command)
        {
            var updateVisitor = GetUpdateSetVisitor(
                _UpdateClause?.Parameters[0]
                    ?? _UpdateExceptClause?.Parameters[0]
                    ?? Expression.Parameter(typeof(T), ""x""),
                ");
            
            #line default
            #line hidden
            
            #line 208 "PostgresqlUpdateCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( ClassName ));
            
            #line default
            #line hidden
            
            #line 208 "PostgresqlUpdateCommandBuilder.tt"
            this.Write(".GetColumnDbName,\n                command);\n\n            // IMPORTANT: only use e" +
                    "xplicit WithFields() when not in AllFields mode\n            if (_UpdateClause !=" +
                    " null && !AllFieldsSet)\n            {\n                var setClause = updateVisi" +
                    "tor.Parse(_UpdateClause);\n                // An empty selector (WithFields(x => " +
                    "new object[] { })) would emit \"SET  WHERE ...\" — malformed\n                // SQ" +
                    "L. Fail with a clear message instead of a Postgres syntax error.\n               " +
                    " if (string.IsNullOrWhiteSpace(setClause))\n                    throw new Invalid" +
                    "OperationException(\n                        \"WithFields(...) selected no columns" +
                    " to update. Select at least one non-key column, or use WithAllFields().\");\n     " +
                    "           return setClause;\n            }\n\n            HashSet<string>? exclude" +
                    "dDbColumns = BuildExcludedDbColumns(command);\n\n            Dictionary<string, Co" +
                    "lumnInfo> allColumns = _TableRow.GetColumns();\n            var sb = new StringBu" +
                    "ilder();\n            bool first = true;\n\n            foreach (var kv in allColum" +
                    "ns)\n            {\n                var dbColumnName = kv.Key;\n                var" +
                    " info = kv.Value;\n\n                if (excludedDbColumns != null && excludedDbCo" +
                    "lumns.Contains(dbColumnName))\n                    continue;\n\n                // " +
                    "Never write the primary key or a serial/auto-increment column into SET. With a c" +
                    "ustom\n                // WHERE that matches multiple rows, writing the instance\'" +
                    "s PK into every matched row would\n                // clobber their keys (duplica" +
                    "te-key error or silent key reassignment).\n                if (info.IsPrimaryKey " +
                    "|| info.IsAutoIncrement)\n                    continue;\n\n                if (!fir" +
                    "st)\n                    sb.Append(\", \");\n\n                first = false;\n\n      " +
                    "          string paramName = $\"@p{command.Parameters.Count}\";\n\n                v" +
                    "ar p = command.CreateParameter()\n                    ?? throw new InvalidOperati" +
                    "onException(\"Expected NpgsqlCommand.\");\n\n                object? dbValue = Norma" +
                    "lizeDbValue(info.Type, info.Value);\n                // Only force the column\'s D" +
                    "B type when the value is actually an enum at runtime, matching the\n             " +
                    "   // insert path. A value convertor may have produced a string for an enum-decl" +
                    "ared column, in which\n                // case forcing GetDbType (e.g. Integer) o" +
                    "nto the string parameter would throw.\n                bool valueIsEnum = info.Va" +
                    "lue != null && info.Value != DBNull.Value && info.Value.GetType().IsEnum;\n\n     " +
                    "           p.ParameterName = paramName;\n                p.Value = dbValue ?? DBN" +
                    "ull.Value;\n\n                if (dbValue == null || dbValue == DBNull.Value || va" +
                    "lueIsEnum)\n                    p.NpgsqlDbType = GetDbType(info.Type);\n\n         " +
                    "       if (info.IsJson)\n                    p.NpgsqlDbType = NpgsqlDbType.Jsonb;" +
                    "\n\n                if (info.IsEncrypted)\n                    p.NpgsqlDbType = Npg" +
                    "sqlDbType.Bytea;\n\n                command.Parameters.Add(p);\n                sb." +
                    "Append($\"\\\"{dbColumnName}\\\" = {paramName}\");\n            }\n\n            return s" +
                    "b.ToString();\n        }\n\n        /// <summary>\n        /// Executes the update c" +
                    "ommand asynchronously against the database connection and returns the number of " +
                    "rows\n        /// affected.\n        /// </summary>\n        /// <remarks>If the da" +
                    "tabase connection is not already open, this method opens it before executing\n   " +
                    "     /// the command. The update is performed using either the specified WHERE c" +
                    "lause or the primary key columns of\n        /// the table row.</remarks>\n       " +
                    " /// <returns>A task that represents the asynchronous operation. The task result" +
                    " contains the number of rows affected by\n        /// the update command. Returns" +
                    " 0 if the command could not be created.</returns>\n        /// <exception cref=\"I" +
                    "nvalidOperationException\">Thrown if a DbBatch was provided, or if no DbConnectio" +
                    "n is available.</exception>\n        public async Task<int> ExecuteAsync(global::" +
                    "System.Threading.CancellationToken cancellationToken = default)\n        {\n#if NE" +
                    "T6_0_OR_GREATER\n            if (_Batch != null)\n                throw new Invali" +
                    "dOperationException(\"Cannot execute command when DbBatch was provided.\");\n#endif" +
                    "\n\n            if (_Connection == null)\n                throw new InvalidOperatio" +
                    "nException(\"No DbConnection provided.\");\n\n            if (_Connection.State != S" +
                    "ystem.Data.ConnectionState.Open)\n                await _Connection.OpenAsync(can" +
                    "cellationToken);\n\n            await using var command = _Connection.CreateComman" +
                    "d() as NpgsqlCommand;\n            if (command == null) return 0;\n\n            if" +
                    " (_Transaction != null)\n                command.Transaction = _Transaction as Np" +
                    "gsqlTransaction;\n\n            string? where = null;\n            if (_WhereClause" +
                    " != null)\n                where = GetWhereVisitor(_WhereClause.Parameters[0], ");
            
            #line default
            #line hidden
            
            #line 309 "PostgresqlUpdateCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( ClassName ));
            
            #line default
            #line hidden
            
            #line 309 "PostgresqlUpdateCommandBuilder.tt"
            this.Write(".GetColumnDbName, command).Parse(_WhereClause);\n            else\n            {\n  " +
                    "              var predicates = new List<string>();\n\n                Dictionary<s" +
                    "tring, ColumnInfo> columns = _TableRow.GetPrimaryColumns();\n                fore" +
                    "ach (var col in columns)\n                {\n                    string paramName " +
                    "= $\"@p{command.Parameters.Count}\";\n                    string colName = col.Key;" +
                    "\n\n                    object? dbValue = NormalizeDbValue(col.Value.Type, col.Val" +
                    "ue.Value);\n                    bool pkValueIsEnum = col.Value.Value != null && c" +
                    "ol.Value.Value != DBNull.Value && col.Value.Value.GetType().IsEnum;\n\n           " +
                    "         var param = new NpgsqlParameter(paramName, dbValue ?? DBNull.Value);\n\n " +
                    "                   if (dbValue == null || dbValue == DBNull.Value || pkValueIsEn" +
                    "um)\n                        param.NpgsqlDbType = GetDbType(col.Value.Type);\n\n   " +
                    "                 command.Parameters.Add(param);\n                    predicates.A" +
                    "dd($\"\\\"{colName}\\\" = {paramName}\");\n                }\n\n                where = \"" +
                    "WHERE \" + string.Join(\" AND \", predicates);\n            }\n\n            command.C" +
                    "ommandText = $@\"\n        UPDATE \"\"{_TableRow.GetTableName()}\"\"\n        SET {Buil" +
                    "dSetClause(command)}\n        {where}\";\n\n            int rowsAffected = await glo" +
                    "bal::Socigy.OpenSource.DB.Core.Diagnostics.DbDiagnostics.ExecuteNonQueryAsync(co" +
                    "mmand, \"UPDATE\", ct => command.ExecuteNonQueryAsync(ct), cancellationToken, _Dia" +
                    "gnostics);\n            return rowsAffected;\n        }\n\n        public NpgsqlDbTy" +
                    "pe GetDbType(Type type)\n        {\n            type = Nullable.GetUnderlyingType(" +
                    "type) ?? type;\n\n            if (type.IsEnum)\n                type = Enum.GetUnde" +
                    "rlyingType(type);\n\n            return type switch\n            {\n                " +
                    "Type t when t == typeof(short) => NpgsqlDbType.Smallint,\n                Type t " +
                    "when t == typeof(byte) => NpgsqlDbType.Smallint,\n                Type t when t =" +
                    "= typeof(sbyte) => NpgsqlDbType.Smallint,\n\n                Type t when t == type" +
                    "of(int) => NpgsqlDbType.Integer,\n                Type t when t == typeof(ushort)" +
                    " => NpgsqlDbType.Integer,\n\n                Type t when t == typeof(long) => Npgs" +
                    "qlDbType.Bigint,\n                Type t when t == typeof(uint) => NpgsqlDbType.B" +
                    "igint,\n\n                Type t when t == typeof(ulong) => NpgsqlDbType.Numeric,\n" +
                    "\n                Type t when t == typeof(string) => NpgsqlDbType.Text,\n         " +
                    "       Type t when t == typeof(bool) => NpgsqlDbType.Boolean,\n                Ty" +
                    "pe t when t == typeof(DateTime) => NpgsqlDbType.Timestamp,\n                Type " +
                    "t when t == typeof(DateTimeOffset) => NpgsqlDbType.TimestampTz,\n                " +
                    "Type t when t == typeof(TimeSpan) => NpgsqlDbType.Interval,\n#if NET6_0_OR_GREATE" +
                    "R\n                Type t when t == typeof(DateOnly) => NpgsqlDbType.Date,\n      " +
                    "          Type t when t == typeof(TimeOnly) => NpgsqlDbType.Time,\n#endif\n       " +
                    "         Type t when t == typeof(float) => NpgsqlDbType.Real,\n                Ty" +
                    "pe t when t == typeof(double) => NpgsqlDbType.Double,\n                Type t whe" +
                    "n t == typeof(decimal) => NpgsqlDbType.Numeric,\n                Type t when t ==" +
                    " typeof(Guid) => NpgsqlDbType.Uuid,\n                Type t when t == typeof(byte" +
                    "[]) => NpgsqlDbType.Bytea,\n                Type t when t == typeof(char) => Npgs" +
                    "qlDbType.Char,\n                _ => NpgsqlDbType.Text\n            };\n        }\n\n" +
                    "        private static bool IsEnumType(Type type)\n        {\n            type = N" +
                    "ullable.GetUnderlyingType(type) ?? type;\n            return type.IsEnum;\n       " +
                    " }\n\n        private static object? NormalizeDbValue(Type type, object? value)\n  " +
                    "      {\n            if (value == null || value == DBNull.Value)\n                " +
                    "return value;\n\n            // Store a Kind=Utc DateTime as a naive \'timestamp\' (" +
                    "relabel Unspecified) so PostgreSQL does not\n            // shift it by the sessi" +
                    "on TimeZone, matching the column type and the insert/COPY paths.\n            if " +
                    "(value is DateTime dt && dt.Kind == DateTimeKind.Utc)\n                return Dat" +
                    "eTime.SpecifyKind(dt, DateTimeKind.Unspecified);\n            // \'timestamptz\' on" +
                    "ly accepts a DateTimeOffset at offset 0; normalize to the same UTC instant.\n    " +
                    "        if (value is DateTimeOffset dto && dto.Offset != TimeSpan.Zero)\n        " +
                    "        return dto.ToUniversalTime();\n            // No Npgsql wire mapping for " +
                    "unsigned CLR types; widen to the signed/decimal type GetDbType targets.\n        " +
                    "    if (value is ushort us) return (int)us;\n            if (value is uint ui) re" +
                    "turn (long)ui;\n            if (value is ulong ul) return (decimal)ul;\n\n         " +
                    "   // Coerce only when the value is *actually* an enum at runtime. A value conve" +
                    "rtor may have already\n            // turned an enum property into its DB represe" +
                    "ntation (e.g. a string), in which case the declared type\n            // is still" +
                    " the enum but the value is not, and coercing it to the underlying integer would " +
                    "throw.\n            // Matches AddInsertParameter in the insert builder.\n        " +
                    "    if (!value.GetType().IsEnum)\n                return value;\n\n            var " +
                    "enumUnderlyingType = Enum.GetUnderlyingType(value.GetType());\n            return" +
                    " Convert.ChangeType(value, enumUnderlyingType);\n        }\n    }\n    ");
            
            #line default
            #line hidden
            
            #line 418 "PostgresqlUpdateCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( CustomPostClass ));
            
            #line default
            #line hidden
            
            #line 418 "PostgresqlUpdateCommandBuilder.tt"
            this.Write("\n}\n\n#nullable disable\n\n");
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        public virtual void Initialize() {
        }
    }
    
    public class PostgresqlUpdateCommandBuilderBase {
        
        private global::System.Text.StringBuilder builder;
        
        private global::System.Collections.Generic.IDictionary<string, object> session;
        
        private global::System.CodeDom.Compiler.CompilerErrorCollection errors;
        
        private string currentIndent = string.Empty;
        
        private global::System.Collections.Generic.Stack<int> indents;
        
        private ToStringInstanceHelper _toStringHelper = new ToStringInstanceHelper();
        
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session {
            get {
                return this.session;
            }
            set {
                this.session = value;
            }
        }
        
        public global::System.Text.StringBuilder GenerationEnvironment {
            get {
                if ((this.builder == null)) {
                    this.builder = new global::System.Text.StringBuilder();
                }
                return this.builder;
            }
            set {
                this.builder = value;
            }
        }
        
        protected global::System.CodeDom.Compiler.CompilerErrorCollection Errors {
            get {
                if ((this.errors == null)) {
                    this.errors = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errors;
            }
        }
        
        public string CurrentIndent {
            get {
                return this.currentIndent;
            }
        }
        
        private global::System.Collections.Generic.Stack<int> Indents {
            get {
                if ((this.indents == null)) {
                    this.indents = new global::System.Collections.Generic.Stack<int>();
                }
                return this.indents;
            }
        }
        
        public ToStringInstanceHelper ToStringHelper {
            get {
                return this._toStringHelper;
            }
        }
        
        public void Error(string message) {
            this.Errors.Add(new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message));
        }
        
        public void Warning(string message) {
            global::System.CodeDom.Compiler.CompilerError val = new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message);
            val.IsWarning = true;
            this.Errors.Add(val);
        }
        
        public string PopIndent() {
            if ((this.Indents.Count == 0)) {
                return string.Empty;
            }
            int lastPos = (this.currentIndent.Length - this.Indents.Pop());
            string last = this.currentIndent.Substring(lastPos);
            this.currentIndent = this.currentIndent.Substring(0, lastPos);
            return last;
        }
        
        public void PushIndent(string indent) {
            this.Indents.Push(indent.Length);
            this.currentIndent = (this.currentIndent + indent);
        }
        
        public void ClearIndent() {
            this.currentIndent = string.Empty;
            this.Indents.Clear();
        }
        
        public void Write(string textToAppend) {
            this.GenerationEnvironment.Append(textToAppend);
        }
        
        public void Write(string format, params object[] args) {
            this.GenerationEnvironment.AppendFormat(format, args);
        }
        
        public void WriteLine(string textToAppend) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendLine(textToAppend);
        }
        
        public void WriteLine(string format, params object[] args) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendFormat(format, args);
            this.GenerationEnvironment.AppendLine();
        }
        
        public class ToStringInstanceHelper {
            
            private global::System.IFormatProvider formatProvider = global::System.Globalization.CultureInfo.InvariantCulture;
            
            public global::System.IFormatProvider FormatProvider {
                get {
                    return this.formatProvider;
                }
                set {
                    if ((value != null)) {
                        this.formatProvider = value;
                    }
                }
            }
            
            public string ToStringWithCulture(object objectToConvert) {
                if ((objectToConvert == null)) {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                global::System.Type type = objectToConvert.GetType();
                global::System.Type iConvertibleType = typeof(global::System.IConvertible);
                if (iConvertibleType.IsAssignableFrom(type)) {
                    return ((global::System.IConvertible)(objectToConvert)).ToString(this.formatProvider);
                }
                global::System.Reflection.MethodInfo methInfo = type.GetMethod("ToString", new global::System.Type[] {
                            iConvertibleType});
                if ((methInfo != null)) {
                    return ((string)(methInfo.Invoke(objectToConvert, new object[] {
                                this.formatProvider})));
                }
                return objectToConvert.ToString();
            }
        }
    }
}
