//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Socigy.OpenSource.DB.SourceGenerator.Templates.CommandBuilders {
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    
    public partial class PostgresqlDeleteCommandBuilder : PostgresqlDeleteCommandBuilderBase {
        
        
        #line 179 "PostgresqlDeleteCommandBuilder.tt"

	public string ClassName { get; set; }
	public string Namespace { get; set; }

    public string CustomPreClass { get; set; } = "";
    public string CustomPostClass { get; set; } = "";

        #line default
        #line hidden
        
        
        public virtual string TransformText() {
            this.GenerationEnvironment = null;
            
            #line 6 "PostgresqlDeleteCommandBuilder.tt"
            this.Write(@"#pragma warning disable
using System;
using System.Text;
using System.Data.Common;
using System.Threading.Tasks;
using System.Linq.Expressions;
using System.Collections.Generic;
using Socigy.OpenSource.DB.Core;
using Socigy.OpenSource.DB.Core.CommandBuilders;
using Socigy.OpenSource.DB.Core.Interfaces;
using Socigy.OpenSource.DB.Core.Delegates;
using Socigy.OpenSource.DB.Core.Parsers;
using Socigy.OpenSource.DB.Core.Parsers.Postgresql;
using Npgsql;
using NpgsqlTypes;
using ");
            
            #line default
            #line hidden
            
            #line 21 "PostgresqlDeleteCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Namespace ));
            
            #line default
            #line hidden
            
            #line 21 "PostgresqlDeleteCommandBuilder.tt"
            this.Write(";\r\n\r\nnamespace Socigy.OpenSource.DB.CommandBuilders.Postgresql\r\n{\r\n    ");
            
            #line default
            #line hidden
            
            #line 25 "PostgresqlDeleteCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( CustomPreClass ));
            
            #line default
            #line hidden
            
            #line 25 "PostgresqlDeleteCommandBuilder.tt"
            this.Write("\r\n    public class Postgresql");
            
            #line default
            #line hidden
            
            #line 26 "PostgresqlDeleteCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( ClassName ));
            
            #line default
            #line hidden
            
            #line 26 "PostgresqlDeleteCommandBuilder.tt"
            this.Write("DeleteCommandBuilder<T> : SqlCommandBuilder<Postgresql");
            
            #line default
            #line hidden
            
            #line 26 "PostgresqlDeleteCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( ClassName ));
            
            #line default
            #line hidden
            
            #line 26 "PostgresqlDeleteCommandBuilder.tt"
            this.Write("DeleteCommandBuilder<T>>\r\n        where T : IDbTable\r\n    {\r\n#if NET6_0_OR_GREATE" +
                    "R\r\n        protected System.Data.Common.DbBatch? _Batch;\r\n\r\n        public Postg" +
                    "resql");
            
            #line default
            #line hidden
            
            #line 32 "PostgresqlDeleteCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( ClassName ));
            
            #line default
            #line hidden
            
            #line 32 "PostgresqlDeleteCommandBuilder.tt"
            this.Write("DeleteCommandBuilder<T> WithBatch(DbBatch? batch)\r\n        {\r\n            if (bat" +
                    "ch == null)\r\n            {\r\n                if (_Connection == null && _Transact" +
                    "ion == null)\r\n                    throw new ArgumentNullException(nameof(batch)," +
                    " \"If batch is null, either connection or transaction must be specified!\");\r\n\r\n  " +
                    "              _Batch = _Connection?.CreateBatch() ?? _Transaction!.Connection?.C" +
                    "reateBatch() ?? throw new InvalidOperationException(\"The provided transaction ha" +
                    "s no DbConnection from which a DbBatch could be created\");\r\n                _Bat" +
                    "ch.Transaction = _Transaction;\r\n            }\r\n            else\r\n               " +
                    " _Batch = batch;\r\n\r\n            return this;\r\n        }\r\n\r\n        public void A" +
                    "ddToBatch()\r\n        {\r\n            if (_Batch == null)\r\n                throw n" +
                    "ew InvalidOperationException(\"Cannot add to batch when no DbBatch was provided. " +
                    "Please call WithBatch() first.\");\r\n\r\n            var batchCommand = _Batch.Creat" +
                    "eBatchCommand();\r\n            _Batch.BatchCommands.Add(batchCommand);\r\n        }" +
                    "\r\n\r\n        public async Task AddToBatchAsync()\r\n        {\r\n            if (_Bat" +
                    "ch == null)\r\n                throw new InvalidOperationException(\"Cannot add to " +
                    "batch when no DbBatch was provided. Please call WithBatch() first.\");\r\n\r\n       " +
                    "     var batchCommand = _Batch.CreateBatchCommand();\r\n            _Batch.BatchCo" +
                    "mmands.Add(batchCommand);\r\n        }\r\n#endif\r\n\r\n        private readonly T? _Tab" +
                    "leRow;\r\n        private Expression<Func<T, bool>>? _WhereClause;\r\n\r\n        publ" +
                    "ic Postgresql");
            
            #line default
            #line hidden
            
            #line 70 "PostgresqlDeleteCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( ClassName ));
            
            #line default
            #line hidden
            
            #line 70 "PostgresqlDeleteCommandBuilder.tt"
            this.Write("DeleteCommandBuilder() { }\r\n        public Postgresql");
            
            #line default
            #line hidden
            
            #line 71 "PostgresqlDeleteCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( ClassName ));
            
            #line default
            #line hidden
            
            #line 71 "PostgresqlDeleteCommandBuilder.tt"
            this.Write("DeleteCommandBuilder(T rowInstance)\r\n        {\r\n            _TableRow = rowInstan" +
                    "ce;\r\n        }\r\n\r\n\r\n        public Postgresql");
            
            #line default
            #line hidden
            
            #line 77 "PostgresqlDeleteCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( ClassName ));
            
            #line default
            #line hidden
            
            #line 77 "PostgresqlDeleteCommandBuilder.tt"
            this.Write(@"DeleteCommandBuilder<T> Where(Expression<Func<T, bool>> where)
        {
            _WhereClause = where;
            return this;
        }

        private ISqlVisitor GetWhereVisitor(ParameterExpression param, GetColumnName getColName, DbCommand command)
        {
            return new PostgresqlWhereVisitor(param, getColName, command);
        }

        public async Task<int> ExecuteAsync()
        {
#if NET6_0_OR_GREATER
            if (_Batch != null)
                throw new InvalidOperationException(""Cannot execute command when DbBatch was provided."");
#endif

            if (_Connection == null)
                throw new InvalidOperationException(""No DbConnection provided."");

            if (_Connection.State != System.Data.ConnectionState.Open)
                await _Connection.OpenAsync();

            await using var command = _Connection.CreateCommand() as NpgsqlCommand;
            if (command == null) return 0;

            if (_Transaction != null)
                command.Transaction = _Transaction as NpgsqlTransaction;

            string where = string.Empty;
            if (_WhereClause != null)
            {
                where = GetWhereVisitor(_WhereClause.Parameters[0], ");
            
            #line default
            #line hidden
            
            #line 110 "PostgresqlDeleteCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( ClassName ));
            
            #line default
            #line hidden
            
            #line 110 "PostgresqlDeleteCommandBuilder.tt"
            this.Write(@".GetColumnDbName, command).Parse(_WhereClause);
            }
            else if (_TableRow != null)
            {
                Dictionary<string, ColumnInfo> columns = _TableRow.GetPrimaryColumns();

                if (columns.Count == 0)
                    throw new InvalidOperationException(""No WHERE clause provided and the entity has no primary keys. Execution aborted to prevent deleting all rows in the table."");

                StringBuilder whereBuilder = new(""WHERE "");
                bool isFirst = true;

                foreach (var col in columns)
                {
                    if (!isFirst)
                        whereBuilder.Append("" AND "");

                    isFirst = false;

                    string colDbName = col.Key;
                    string paramName = $""@p{command.Parameters.Count}"";

                    whereBuilder.Append($""\""{colDbName}\"" = {paramName}"");

                    NpgsqlParameter param = new(paramName, GetDbType(col.Value.Type))
                    {
                        Value = col.Value.Value ?? DBNull.Value
                    };

                    command.Parameters.Add(param);
                }

                where = whereBuilder.ToString();
            }

            command.CommandText = $@""
        DELETE FROM """"{");
            
            #line default
            #line hidden
            
            #line 146 "PostgresqlDeleteCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( ClassName ));
            
            #line default
            #line hidden
            
            #line 146 "PostgresqlDeleteCommandBuilder.tt"
            this.Write(@".TableName}""""
        {where}"";

            return await global::Socigy.OpenSource.DB.Core.Diagnostics.DbDiagnostics.ExecuteNonQueryAsync(command, ""DELETE"", ct => command.ExecuteNonQueryAsync(ct), default, _Diagnostics);
        }

        public NpgsqlDbType GetDbType(Type type)
        {
            type = Nullable.GetUnderlyingType(type) ?? type;

            return type switch
            {
                Type t when t == typeof(int) => NpgsqlDbType.Integer,
                Type t when t == typeof(long) => NpgsqlDbType.Bigint,
                Type t when t == typeof(string) => NpgsqlDbType.Text,
                Type t when t == typeof(bool) => NpgsqlDbType.Boolean,
                Type t when t == typeof(DateTime) => NpgsqlDbType.Timestamp,
                Type t when t == typeof(float) => NpgsqlDbType.Real,
                Type t when t == typeof(double) => NpgsqlDbType.Double,
                Type t when t == typeof(decimal) => NpgsqlDbType.Numeric,
                Type t when t == typeof(Guid) => NpgsqlDbType.Uuid,
                Type t when t == typeof(byte[]) => NpgsqlDbType.Bytea,
                Type t when t == typeof(short) => NpgsqlDbType.Smallint,
                Type t when t == typeof(char) => NpgsqlDbType.Char,
                _ => NpgsqlDbType.Text
            };
        }
    }
    ");
            
            #line default
            #line hidden
            
            #line 174 "PostgresqlDeleteCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( CustomPostClass ));
            
            #line default
            #line hidden
            
            #line 174 "PostgresqlDeleteCommandBuilder.tt"
            this.Write("\r\n}\r\n\r\n#nullable disable\r\n\r\n");
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        public virtual void Initialize() {
        }
    }
    
    public class PostgresqlDeleteCommandBuilderBase {
        
        private global::System.Text.StringBuilder builder;
        
        private global::System.Collections.Generic.IDictionary<string, object> session;
        
        private global::System.CodeDom.Compiler.CompilerErrorCollection errors;
        
        private string currentIndent = string.Empty;
        
        private global::System.Collections.Generic.Stack<int> indents;
        
        private ToStringInstanceHelper _toStringHelper = new ToStringInstanceHelper();
        
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session {
            get {
                return this.session;
            }
            set {
                this.session = value;
            }
        }
        
        public global::System.Text.StringBuilder GenerationEnvironment {
            get {
                if ((this.builder == null)) {
                    this.builder = new global::System.Text.StringBuilder();
                }
                return this.builder;
            }
            set {
                this.builder = value;
            }
        }
        
        protected global::System.CodeDom.Compiler.CompilerErrorCollection Errors {
            get {
                if ((this.errors == null)) {
                    this.errors = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errors;
            }
        }
        
        public string CurrentIndent {
            get {
                return this.currentIndent;
            }
        }
        
        private global::System.Collections.Generic.Stack<int> Indents {
            get {
                if ((this.indents == null)) {
                    this.indents = new global::System.Collections.Generic.Stack<int>();
                }
                return this.indents;
            }
        }
        
        public ToStringInstanceHelper ToStringHelper {
            get {
                return this._toStringHelper;
            }
        }
        
        public void Error(string message) {
            this.Errors.Add(new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message));
        }
        
        public void Warning(string message) {
            global::System.CodeDom.Compiler.CompilerError val = new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message);
            val.IsWarning = true;
            this.Errors.Add(val);
        }
        
        public string PopIndent() {
            if ((this.Indents.Count == 0)) {
                return string.Empty;
            }
            int lastPos = (this.currentIndent.Length - this.Indents.Pop());
            string last = this.currentIndent.Substring(lastPos);
            this.currentIndent = this.currentIndent.Substring(0, lastPos);
            return last;
        }
        
        public void PushIndent(string indent) {
            this.Indents.Push(indent.Length);
            this.currentIndent = (this.currentIndent + indent);
        }
        
        public void ClearIndent() {
            this.currentIndent = string.Empty;
            this.Indents.Clear();
        }
        
        public void Write(string textToAppend) {
            this.GenerationEnvironment.Append(textToAppend);
        }
        
        public void Write(string format, params object[] args) {
            this.GenerationEnvironment.AppendFormat(format, args);
        }
        
        public void WriteLine(string textToAppend) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendLine(textToAppend);
        }
        
        public void WriteLine(string format, params object[] args) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendFormat(format, args);
            this.GenerationEnvironment.AppendLine();
        }
        
        public class ToStringInstanceHelper {
            
            private global::System.IFormatProvider formatProvider = global::System.Globalization.CultureInfo.InvariantCulture;
            
            public global::System.IFormatProvider FormatProvider {
                get {
                    return this.formatProvider;
                }
                set {
                    if ((value != null)) {
                        this.formatProvider = value;
                    }
                }
            }
            
            public string ToStringWithCulture(object objectToConvert) {
                if ((objectToConvert == null)) {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                global::System.Type type = objectToConvert.GetType();
                global::System.Type iConvertibleType = typeof(global::System.IConvertible);
                if (iConvertibleType.IsAssignableFrom(type)) {
                    return ((global::System.IConvertible)(objectToConvert)).ToString(this.formatProvider);
                }
                global::System.Reflection.MethodInfo methInfo = type.GetMethod("ToString", new global::System.Type[] {
                            iConvertibleType});
                if ((methInfo != null)) {
                    return ((string)(methInfo.Invoke(objectToConvert, new object[] {
                                this.formatProvider})));
                }
                return objectToConvert.ToString();
            }
        }
    }
}
