//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Socigy.OpenSource.DB.SourceGenerator.Templates {
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    
    public partial class DbConnectionFactoryTemplate : DbConnectionFactoryTemplateBase {
        
        
        #line 191 "DbConnectionFactoryTemplate.tt"

    public string BaseNamespace { get; set; }

    public string DatabasePrefix { get; set; }
    public IEnumerable<string> Usings { get; set; }
    public string ConnectionClassName { get; set; }

        #line default
        #line hidden
        
        
        public virtual string TransformText() {
            this.GenerationEnvironment = null;
            
            #line 6 "DbConnectionFactoryTemplate.tt"
            this.Write(@"#pragma warning disable
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Hosting;
using Socigy.OpenSource.DB.Core;
using Socigy.OpenSource.DB.Core.Credentials;
using System.Data.Common;
using System.Security;
");
            
            #line default
            #line hidden
            
            #line 15 "DbConnectionFactoryTemplate.tt"

    foreach (var usingString in Usings)
    {

            
            #line default
            #line hidden
            
            #line 19 "DbConnectionFactoryTemplate.tt"
            this.Write("using ");
            
            #line default
            #line hidden
            
            #line 19 "DbConnectionFactoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( usingString ));
            
            #line default
            #line hidden
            
            #line 19 "DbConnectionFactoryTemplate.tt"
            this.Write(";\r\n");
            
            #line default
            #line hidden
            
            #line 20 "DbConnectionFactoryTemplate.tt"

    }

            
            #line default
            #line hidden
            
            #line 23 "DbConnectionFactoryTemplate.tt"
            this.Write("\r\n#nullable enable\r\n\r\nnamespace ");
            
            #line default
            #line hidden
            
            #line 26 "DbConnectionFactoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( BaseNamespace ));
            
            #line default
            #line hidden
            
            #line 26 "DbConnectionFactoryTemplate.tt"
            this.Write("\r\n{\r\n    public class ");
            
            #line default
            #line hidden
            
            #line 28 "DbConnectionFactoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( DatabasePrefix ));
            
            #line default
            #line hidden
            
            #line 28 "DbConnectionFactoryTemplate.tt"
            this.Write("ConnectionFactory : IDbConnectionFactory, IHostedLifecycleService\r\n    {\r\n       " +
                    " private readonly IConfiguration _Configuration;\r\n        private readonly strin" +
                    "g? _ServiceKey;\r\n\r\n        private readonly ILogger _Logger;\r\n        private re" +
                    "adonly string? _ConnectionString;\r\n        // Optional: when a credential provid" +
                    "er is registered (e.g. HashiCorp Vault), it supplies a\r\n        // dynamically-r" +
                    "otated base connection string; otherwise the static config string is used.\r\n    " +
                    "    private readonly IDbCredentialsProvider? _Credentials;\r\n        public Postg" +
                    "resqlConnectionFactory(ILogger<PostgresqlConnectionFactory> logger, IConfigurati" +
                    "on configuration, [ServiceKey] object? key, IDbCredentialsProvider? credentials " +
                    "= null)\r\n        {\r\n            _Configuration = configuration;\r\n            _Se" +
                    "rviceKey = key as string;\r\n            _Logger = logger;\r\n            _Credentia" +
                    "ls = credentials;\r\n\r\n            var connStrings = _Configuration.GetRequiredSec" +
                    "tion(\"ConnectionStrings\");\r\n            if (!string.IsNullOrEmpty(_ServiceKey))\r" +
                    "\n                connStrings = connStrings.GetSection(_ServiceKey);\r\n\r\n         " +
                    "   var connectionString = connStrings[\"Default\"];\r\n            if (connectionStr" +
                    "ing == null)\r\n            {\r\n                if (key != null)\r\n                 " +
                    "   logger.LogWarning($\"No default connection string for database {key} was found" +
                    "!\");\r\n                else\r\n                    logger.LogWarning(\"No default co" +
                    "nnection string was found!\");\r\n\r\n                return;\r\n            }\r\n\r\n     " +
                    "       _ConnectionString = connectionString;\r\n        }\r\n\r\n        public async " +
                    "Task<bool> EnsureDbExists()\r\n        {\r\n            if (_ServiceKey == null)\r\n  " +
                    "          {\r\n                string message = \"No service key (database name) wa" +
                    "s provided to this connection factory instance. Unable to ensure that the databa" +
                    "se exist!\";\r\n                _Logger.LogCritical(message);\r\n                thro" +
                    "w new InvalidDataException(message);\r\n            }\r\n\r\n            // Prime/refr" +
                    "esh dynamic credentials (e.g. Vault) before resolving the connection string.\r\n  " +
                    "          if (_Credentials != null)\r\n            {\r\n                _Logger.LogI" +
                    "nformation(\"Refreshing rotating credentials for database {Database} via {Provide" +
                    "r}\", _ServiceKey, _Credentials.GetType().Name);\r\n                await _Credenti" +
                    "als.RefreshAsync(_ServiceKey, null);\r\n            }\r\n\r\n            var baseConne" +
                    "ctionString = ResolveBaseConnectionString(null);\r\n            if (baseConnection" +
                    "String == null)\r\n            {\r\n                string message = $\"Failed to ens" +
                    "ure that the {_ServiceKey} database exists, because no ConnectionString was prov" +
                    "ided!\";\r\n                _Logger.LogCritical(message);\r\n                throw ne" +
                    "w InvalidDataException(message);\r\n            }\r\n\r\n            // Connect to the" +
                    " default \'postgres\' database to check/create the new database\r\n            var m" +
                    "asterConnectionBuilder = new NpgsqlConnectionStringBuilder(baseConnectionString)" +
                    "\r\n            {\r\n                Database = \"postgres\"\r\n            };\r\n\r\n      " +
                    "      bool databaseExists = false;\r\n\r\n            using (var connection = new Np" +
                    "gsqlConnection(masterConnectionBuilder.ToString()))\r\n            {\r\n            " +
                    "    await connection.OpenAsync();\r\n\r\n                using (var command = connec" +
                    "tion.CreateCommand())\r\n                {\r\n                    command.CommandTex" +
                    "t = \"SELECT 1 FROM pg_database WHERE datname = @databaseName\";\r\n                " +
                    "    command.Parameters.Add(new NpgsqlParameter(\"databaseName\", _ServiceKey));\r\n " +
                    "                   \r\n                    var result = await global::Socigy.OpenS" +
                    "ource.DB.Core.Diagnostics.DbDiagnostics.ExecuteScalarAsync(command, \"DDL\", ct =>" +
                    " command.ExecuteScalarAsync(ct));\r\n                    databaseExists = result !" +
                    "= null;\r\n                }\r\n\r\n                if (!databaseExists)\r\n            " +
                    "    {\r\n                    using (var command = connection.CreateCommand())\r\n   " +
                    "                 {\r\n                        command.CommandText = $\"CREATE DATAB" +
                    "ASE \\\"{_ServiceKey}\\\"\";\r\n                        await global::Socigy.OpenSource" +
                    ".DB.Core.Diagnostics.DbDiagnostics.ExecuteNonQueryAsync(command, \"DDL\", ct => co" +
                    "mmand.ExecuteNonQueryAsync(ct));\r\n                    }\r\n                }\r\n    " +
                    "        }\r\n\r\n            return databaseExists;\r\n        }\r\n\r\n        private st" +
                    "ring? GetConnectionString(string key)\r\n        {\r\n            var connStrings = " +
                    "_Configuration.GetRequiredSection(\"ConnectionStrings\");\r\n            if (!string" +
                    ".IsNullOrEmpty(_ServiceKey))\r\n                connStrings = connStrings.GetSecti" +
                    "on(_ServiceKey);\r\n\r\n            return connStrings[key];\r\n        }\r\n\r\n        /" +
                    "/ Resolves the base connection string (without Database=...): the credential pro" +
                    "vider wins when\r\n        // present (rotating creds), then a named config key, t" +
                    "hen the default config string.\r\n        private string? ResolveBaseConnectionStr" +
                    "ing(string? connectionKey)\r\n        {\r\n            if (_Credentials != null)\r\n  " +
                    "          {\r\n                var fromProvider = _Credentials.GetConnectionString" +
                    "(_ServiceKey ?? string.Empty, connectionKey);\r\n                if (!string.IsNul" +
                    "lOrEmpty(fromProvider))\r\n                    return fromProvider;\r\n            }" +
                    "\r\n\r\n            if (connectionKey != null)\r\n            {\r\n                var n" +
                    "amed = GetConnectionString(connectionKey);\r\n                if (!string.IsNullOr" +
                    "Empty(named))\r\n                    return named;\r\n            }\r\n\r\n            r" +
                    "eturn _ConnectionString;\r\n        }\r\n\r\n        public DbConnection Create(string" +
                    "? connectionKey = null)\r\n        {\r\n            string connectionString = Resolv" +
                    "eBaseConnectionString(connectionKey)\r\n                ?? throw new InvalidDataEx" +
                    "ception(\"Unable to create DbConnection without a ConnectionString. Please provid" +
                    "e a connection string (or register an IDbCredentialsProvider) and try again!\");\r" +
                    "\n\r\n            // Connecting to the correct database\r\n            connectionStri" +
                    "ng = connectionString.TrimEnd().TrimEnd(\';\') + $\";Database={_ServiceKey}\";\r\n\r\n  " +
                    "          return new NpgsqlConnection(connectionString);\r\n        }\r\n\r\n        p" +
                    "ublic async Task StartAsync(CancellationToken cancellationToken)\r\n        {\r\n   " +
                    "         if (_ServiceKey != null && (_ConnectionString != null || _Credentials !" +
                    "= null))\r\n                await EnsureDbExists();\r\n        }\r\n\r\n        #region " +
                    "HostedLifeCycle\r\n        public async Task StartedAsync(CancellationToken cancel" +
                    "lationToken)\r\n        {\r\n        }\r\n        public async Task StartingAsync(Canc" +
                    "ellationToken cancellationToken)\r\n        {\r\n\r\n        }\r\n        public async T" +
                    "ask StoppedAsync(CancellationToken cancellationToken)\r\n        {\r\n        }\r\n   " +
                    "     public async Task StoppingAsync(CancellationToken cancellationToken)\r\n     " +
                    "   {\r\n        }\r\n        public async Task StopAsync(CancellationToken cancellat" +
                    "ionToken)\r\n        {\r\n        }\r\n        #endregion\r\n    }\r\n}\r\n\r\n#nullable disab" +
                    "le\r\n\r\n");
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        public virtual void Initialize() {
        }
    }
    
    public class DbConnectionFactoryTemplateBase {
        
        private global::System.Text.StringBuilder builder;
        
        private global::System.Collections.Generic.IDictionary<string, object> session;
        
        private global::System.CodeDom.Compiler.CompilerErrorCollection errors;
        
        private string currentIndent = string.Empty;
        
        private global::System.Collections.Generic.Stack<int> indents;
        
        private ToStringInstanceHelper _toStringHelper = new ToStringInstanceHelper();
        
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session {
            get {
                return this.session;
            }
            set {
                this.session = value;
            }
        }
        
        public global::System.Text.StringBuilder GenerationEnvironment {
            get {
                if ((this.builder == null)) {
                    this.builder = new global::System.Text.StringBuilder();
                }
                return this.builder;
            }
            set {
                this.builder = value;
            }
        }
        
        protected global::System.CodeDom.Compiler.CompilerErrorCollection Errors {
            get {
                if ((this.errors == null)) {
                    this.errors = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errors;
            }
        }
        
        public string CurrentIndent {
            get {
                return this.currentIndent;
            }
        }
        
        private global::System.Collections.Generic.Stack<int> Indents {
            get {
                if ((this.indents == null)) {
                    this.indents = new global::System.Collections.Generic.Stack<int>();
                }
                return this.indents;
            }
        }
        
        public ToStringInstanceHelper ToStringHelper {
            get {
                return this._toStringHelper;
            }
        }
        
        public void Error(string message) {
            this.Errors.Add(new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message));
        }
        
        public void Warning(string message) {
            global::System.CodeDom.Compiler.CompilerError val = new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message);
            val.IsWarning = true;
            this.Errors.Add(val);
        }
        
        public string PopIndent() {
            if ((this.Indents.Count == 0)) {
                return string.Empty;
            }
            int lastPos = (this.currentIndent.Length - this.Indents.Pop());
            string last = this.currentIndent.Substring(lastPos);
            this.currentIndent = this.currentIndent.Substring(0, lastPos);
            return last;
        }
        
        public void PushIndent(string indent) {
            this.Indents.Push(indent.Length);
            this.currentIndent = (this.currentIndent + indent);
        }
        
        public void ClearIndent() {
            this.currentIndent = string.Empty;
            this.Indents.Clear();
        }
        
        public void Write(string textToAppend) {
            this.GenerationEnvironment.Append(textToAppend);
        }
        
        public void Write(string format, params object[] args) {
            this.GenerationEnvironment.AppendFormat(format, args);
        }
        
        public void WriteLine(string textToAppend) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendLine(textToAppend);
        }
        
        public void WriteLine(string format, params object[] args) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendFormat(format, args);
            this.GenerationEnvironment.AppendLine();
        }
        
        public class ToStringInstanceHelper {
            
            private global::System.IFormatProvider formatProvider = global::System.Globalization.CultureInfo.InvariantCulture;
            
            public global::System.IFormatProvider FormatProvider {
                get {
                    return this.formatProvider;
                }
                set {
                    if ((value != null)) {
                        this.formatProvider = value;
                    }
                }
            }
            
            public string ToStringWithCulture(object objectToConvert) {
                if ((objectToConvert == null)) {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                global::System.Type type = objectToConvert.GetType();
                global::System.Type iConvertibleType = typeof(global::System.IConvertible);
                if (iConvertibleType.IsAssignableFrom(type)) {
                    return ((global::System.IConvertible)(objectToConvert)).ToString(this.formatProvider);
                }
                global::System.Reflection.MethodInfo methInfo = type.GetMethod("ToString", new global::System.Type[] {
                            iConvertibleType});
                if ((methInfo != null)) {
                    return ((string)(methInfo.Invoke(objectToConvert, new object[] {
                                this.formatProvider})));
                }
                return objectToConvert.ToString();
            }
        }
    }
}
