//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Socigy.OpenSource.DB.SourceGenerator.Templates {
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    
    public partial class DbConnectionFactoryTemplate : DbConnectionFactoryTemplateBase {
        
        
        #line 215 "DbConnectionFactoryTemplate.tt"

    public string BaseNamespace { get; set; }

    public string DatabasePrefix { get; set; }
    public IEnumerable<string> Usings { get; set; }
    public string ConnectionClassName { get; set; }

        #line default
        #line hidden
        
        
        public virtual string TransformText() {
            this.GenerationEnvironment = null;
            
            #line 6 "DbConnectionFactoryTemplate.tt"
            this.Write(@"#pragma warning disable
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Hosting;
using Socigy.OpenSource.DB.Core;
using Socigy.OpenSource.DB.Core.Credentials;
using System.Data.Common;
using System.Security;
");
            
            #line default
            #line hidden
            
            #line 15 "DbConnectionFactoryTemplate.tt"

    foreach (var usingString in Usings)
    {

            
            #line default
            #line hidden
            
            #line 19 "DbConnectionFactoryTemplate.tt"
            this.Write("using ");
            
            #line default
            #line hidden
            
            #line 19 "DbConnectionFactoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( usingString ));
            
            #line default
            #line hidden
            
            #line 19 "DbConnectionFactoryTemplate.tt"
            this.Write(";\n");
            
            #line default
            #line hidden
            
            #line 20 "DbConnectionFactoryTemplate.tt"

    }

            
            #line default
            #line hidden
            
            #line 23 "DbConnectionFactoryTemplate.tt"
            this.Write("\n#nullable enable\n\nnamespace ");
            
            #line default
            #line hidden
            
            #line 26 "DbConnectionFactoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( BaseNamespace ));
            
            #line default
            #line hidden
            
            #line 26 "DbConnectionFactoryTemplate.tt"
            this.Write("\n{\n    public class ");
            
            #line default
            #line hidden
            
            #line 28 "DbConnectionFactoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( DatabasePrefix ));
            
            #line default
            #line hidden
            
            #line 28 "DbConnectionFactoryTemplate.tt"
            this.Write(@"ConnectionFactory : IDbConnectionFactory, IHostedLifecycleService
    {
        private readonly IConfiguration _Configuration;
        private readonly string? _ServiceKey;

        private readonly ILogger _Logger;
        private readonly string? _ConnectionString;
        // Optional: when a credential provider is registered (e.g. HashiCorp Vault), it supplies a
        // dynamically-rotated base connection string; otherwise the static config string is used.
        private readonly IDbCredentialsProvider? _Credentials;
        // Optional: a credential provider that owns its own pool (and disposes it on rotation) rather than
        // handing back a connection string. Preferred when present — see IDbConnectionSource for why.
        private readonly IDbConnectionSource? _ConnectionSource;
        public ");
            
            #line default
            #line hidden
            
            #line 41 "DbConnectionFactoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( DatabasePrefix ));
            
            #line default
            #line hidden
            
            #line 41 "DbConnectionFactoryTemplate.tt"
            this.Write("ConnectionFactory(ILogger<");
            
            #line default
            #line hidden
            
            #line 41 "DbConnectionFactoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( DatabasePrefix ));
            
            #line default
            #line hidden
            
            #line 41 "DbConnectionFactoryTemplate.tt"
            this.Write("ConnectionFactory> logger, IConfiguration configuration, [ServiceKey] object? key" +
                    ", IDbCredentialsProvider? credentials = null)\n        {\n            _Configurati" +
                    "on = configuration;\n            _ServiceKey = key as string;\n            _Logger" +
                    " = logger;\n            _Credentials = credentials;\n            _ConnectionSource" +
                    " = credentials as IDbConnectionSource;\n\n            var connStrings = _Configura" +
                    "tion.GetRequiredSection(\"ConnectionStrings\");\n            if (!string.IsNullOrEm" +
                    "pty(_ServiceKey))\n                connStrings = connStrings.GetSection(_ServiceK" +
                    "ey);\n\n            var connectionString = connStrings[\"Default\"];\n            if " +
                    "(connectionString == null)\n            {\n                if (key != null)\n      " +
                    "              logger.LogWarning($\"No default connection string for database {key" +
                    "} was found!\");\n                else\n                    logger.LogWarning(\"No d" +
                    "efault connection string was found!\");\n\n                return;\n            }\n\n " +
                    "           _ConnectionString = connectionString;\n        }\n\n        public async" +
                    " Task<bool> EnsureDbExists()\n        {\n            if (_ServiceKey == null)\n    " +
                    "        {\n                string message = \"No service key (database name) was p" +
                    "rovided to this connection factory instance. Unable to ensure that the database " +
                    "exist!\";\n                _Logger.LogCritical(message);\n                throw new" +
                    " InvalidDataException(message);\n            }\n\n            // Prime/refresh dyna" +
                    "mic credentials (e.g. Vault) before resolving the connection string.\n           " +
                    " if (_Credentials != null)\n            {\n                _Logger.LogInformation(" +
                    "\"Refreshing rotating credentials for database {Database} via {Provider}\", _Servi" +
                    "ceKey, _Credentials.GetType().Name);\n                await _Credentials.RefreshA" +
                    "sync(_ServiceKey, null);\n            }\n\n            var baseConnectionString = R" +
                    "esolveBaseConnectionString(null);\n            if (baseConnectionString == null)\n" +
                    "            {\n                string message = $\"Failed to ensure that the {_Ser" +
                    "viceKey} database exists, because no ConnectionString was provided!\";\n          " +
                    "      _Logger.LogCritical(message);\n                throw new InvalidDataExcepti" +
                    "on(message);\n            }\n\n            // Connect to the default \'postgres\' dat" +
                    "abase to check/create the new database\n            var masterConnectionBuilder =" +
                    " new NpgsqlConnectionStringBuilder(baseConnectionString)\n            {\n         " +
                    "       Database = \"postgres\"\n            };\n\n            bool databaseExists = f" +
                    "alse;\n\n            using (var connection = new NpgsqlConnection(masterConnection" +
                    "Builder.ToString()))\n            {\n                await connection.OpenAsync();" +
                    "\n\n                using (var command = connection.CreateCommand())\n             " +
                    "   {\n                    command.CommandText = \"SELECT 1 FROM pg_database WHERE " +
                    "datname = @databaseName\";\n                    command.Parameters.Add(new NpgsqlP" +
                    "arameter(\"databaseName\", _ServiceKey));\n                    \n                   " +
                    " var result = await global::Socigy.OpenSource.DB.Core.Diagnostics.DbDiagnostics." +
                    "ExecuteScalarAsync(command, \"DDL\", ct => command.ExecuteScalarAsync(ct));\n      " +
                    "              databaseExists = result != null;\n                }\n\n              " +
                    "  if (!databaseExists)\n                {\n                    using (var command " +
                    "= connection.CreateCommand())\n                    {\n                        comm" +
                    "and.CommandText = $\"CREATE DATABASE \\\"{_ServiceKey}\\\"\";\n                        " +
                    "try\n                        {\n                            await global::Socigy.O" +
                    "penSource.DB.Core.Diagnostics.DbDiagnostics.ExecuteNonQueryAsync(command, \"DDL\"," +
                    " ct => command.ExecuteNonQueryAsync(ct));\n                        }\n            " +
                    "            catch (global::Npgsql.PostgresException __ex) when (__ex.SqlState ==" +
                    " \"42P04\" || __ex.SqlState == \"23505\")\n                        {\n                " +
                    "            // Another replica created the database first. CREATE DATABASE has n" +
                    "o IF NOT EXISTS\n                            // and can\'t run in a transaction, s" +
                    "o a concurrent-startup race surfaces as\n                            // 42P04 dup" +
                    "licate_database (or 23505 on the pg_database insert). Treat as success.\n        " +
                    "                    databaseExists = true;\n                        }\n           " +
                    "         }\n                }\n            }\n\n            return databaseExists;\n " +
                    "       }\n\n        private string? GetConnectionString(string key)\n        {\n    " +
                    "        var connStrings = _Configuration.GetRequiredSection(\"ConnectionStrings\")" +
                    ";\n            if (!string.IsNullOrEmpty(_ServiceKey))\n                connString" +
                    "s = connStrings.GetSection(_ServiceKey);\n\n            return connStrings[key];\n " +
                    "       }\n\n        // Resolves the base connection string (without Database=...):" +
                    " the credential provider wins when\n        // present (rotating creds), then a n" +
                    "amed config key, then the default config string.\n        private string? Resolve" +
                    "BaseConnectionString(string? connectionKey)\n        {\n            if (_Credentia" +
                    "ls != null)\n            {\n                var fromProvider = _Credentials.GetCon" +
                    "nectionString(_ServiceKey ?? string.Empty, connectionKey);\n                if (!" +
                    "string.IsNullOrEmpty(fromProvider))\n                    return fromProvider;\n   " +
                    "         }\n\n            if (connectionKey != null)\n            {\n               " +
                    " var named = GetConnectionString(connectionKey);\n                if (!string.IsN" +
                    "ullOrEmpty(named))\n                    return named;\n            }\n\n            " +
                    "return _ConnectionString;\n        }\n\n        public DbConnection Create(string? " +
                    "connectionKey = null)\n        {\n            // A provider that owns its pool win" +
                    "s: it disposes the old pool when credentials rotate, whereas\n            // hand" +
                    "ing back a changed connection string makes Npgsql open a new pool and strand the" +
                    " previous\n            // one for the life of the process (its PoolManager keys b" +
                    "y exact string and never evicts).\n            if (_ConnectionSource != null)\n   " +
                    "         {\n                var pooled = _ConnectionSource.CreateConnection(_Serv" +
                    "iceKey ?? string.Empty, connectionKey);\n                if (pooled != null)\n    " +
                    "                return pooled;\n            }\n\n            string connectionStrin" +
                    "g = ResolveBaseConnectionString(connectionKey)\n                ?? throw new Inva" +
                    "lidDataException(\"Unable to create DbConnection without a ConnectionString. Plea" +
                    "se provide a connection string (or register an IDbCredentialsProvider) and try a" +
                    "gain!\");\n\n            // Connecting to the correct database\n            connecti" +
                    "onString = connectionString.TrimEnd().TrimEnd(\';\') + $\";Database={_ServiceKey}\";" +
                    "\n\n            return new NpgsqlConnection(connectionString);\n        }\n\n        " +
                    "public async Task StartAsync(CancellationToken cancellationToken)\n        {\n    " +
                    "        if (_ServiceKey != null && (_ConnectionString != null || _Credentials !=" +
                    " null))\n                await EnsureDbExists();\n        }\n\n        #region Hoste" +
                    "dLifeCycle\n        public async Task StartedAsync(CancellationToken cancellation" +
                    "Token)\n        {\n        }\n        public async Task StartingAsync(CancellationT" +
                    "oken cancellationToken)\n        {\n\n        }\n        public async Task StoppedAs" +
                    "ync(CancellationToken cancellationToken)\n        {\n        }\n        public asyn" +
                    "c Task StoppingAsync(CancellationToken cancellationToken)\n        {\n        }\n  " +
                    "      public async Task StopAsync(CancellationToken cancellationToken)\n        {" +
                    "\n        }\n        #endregion\n    }\n}\n\n#nullable disable\n\n");
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        public virtual void Initialize() {
        }
    }
    
    public class DbConnectionFactoryTemplateBase {
        
        private global::System.Text.StringBuilder builder;
        
        private global::System.Collections.Generic.IDictionary<string, object> session;
        
        private global::System.CodeDom.Compiler.CompilerErrorCollection errors;
        
        private string currentIndent = string.Empty;
        
        private global::System.Collections.Generic.Stack<int> indents;
        
        private ToStringInstanceHelper _toStringHelper = new ToStringInstanceHelper();
        
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session {
            get {
                return this.session;
            }
            set {
                this.session = value;
            }
        }
        
        public global::System.Text.StringBuilder GenerationEnvironment {
            get {
                if ((this.builder == null)) {
                    this.builder = new global::System.Text.StringBuilder();
                }
                return this.builder;
            }
            set {
                this.builder = value;
            }
        }
        
        protected global::System.CodeDom.Compiler.CompilerErrorCollection Errors {
            get {
                if ((this.errors == null)) {
                    this.errors = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errors;
            }
        }
        
        public string CurrentIndent {
            get {
                return this.currentIndent;
            }
        }
        
        private global::System.Collections.Generic.Stack<int> Indents {
            get {
                if ((this.indents == null)) {
                    this.indents = new global::System.Collections.Generic.Stack<int>();
                }
                return this.indents;
            }
        }
        
        public ToStringInstanceHelper ToStringHelper {
            get {
                return this._toStringHelper;
            }
        }
        
        public void Error(string message) {
            this.Errors.Add(new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message));
        }
        
        public void Warning(string message) {
            global::System.CodeDom.Compiler.CompilerError val = new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message);
            val.IsWarning = true;
            this.Errors.Add(val);
        }
        
        public string PopIndent() {
            if ((this.Indents.Count == 0)) {
                return string.Empty;
            }
            int lastPos = (this.currentIndent.Length - this.Indents.Pop());
            string last = this.currentIndent.Substring(lastPos);
            this.currentIndent = this.currentIndent.Substring(0, lastPos);
            return last;
        }
        
        public void PushIndent(string indent) {
            this.Indents.Push(indent.Length);
            this.currentIndent = (this.currentIndent + indent);
        }
        
        public void ClearIndent() {
            this.currentIndent = string.Empty;
            this.Indents.Clear();
        }
        
        public void Write(string textToAppend) {
            this.GenerationEnvironment.Append(textToAppend);
        }
        
        public void Write(string format, params object[] args) {
            this.GenerationEnvironment.AppendFormat(format, args);
        }
        
        public void WriteLine(string textToAppend) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendLine(textToAppend);
        }
        
        public void WriteLine(string format, params object[] args) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendFormat(format, args);
            this.GenerationEnvironment.AppendLine();
        }
        
        public class ToStringInstanceHelper {
            
            private global::System.IFormatProvider formatProvider = global::System.Globalization.CultureInfo.InvariantCulture;
            
            public global::System.IFormatProvider FormatProvider {
                get {
                    return this.formatProvider;
                }
                set {
                    if ((value != null)) {
                        this.formatProvider = value;
                    }
                }
            }
            
            public string ToStringWithCulture(object objectToConvert) {
                if ((objectToConvert == null)) {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                global::System.Type type = objectToConvert.GetType();
                global::System.Type iConvertibleType = typeof(global::System.IConvertible);
                if (iConvertibleType.IsAssignableFrom(type)) {
                    return ((global::System.IConvertible)(objectToConvert)).ToString(this.formatProvider);
                }
                global::System.Reflection.MethodInfo methInfo = type.GetMethod("ToString", new global::System.Type[] {
                            iConvertibleType});
                if ((methInfo != null)) {
                    return ((string)(methInfo.Invoke(objectToConvert, new object[] {
                                this.formatProvider})));
                }
                return objectToConvert.ToString();
            }
        }
    }
}
