//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Socigy.OpenSource.DB.SourceGenerator.Templates {
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    
    public partial class DbConnectionFactoryTemplate : DbConnectionFactoryTemplateBase {
        
        
        #line 159 "DbConnectionFactoryTemplate.tt"

    public string BaseNamespace { get; set; }

    public string DatabasePrefix { get; set; }
    public IEnumerable<string> Usings { get; set; }
    public string ConnectionClassName { get; set; }

        #line default
        #line hidden
        
        
        public virtual string TransformText() {
            this.GenerationEnvironment = null;
            
            #line 6 "DbConnectionFactoryTemplate.tt"
            this.Write(@"#pragma warning disable
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Hosting;
using Socigy.OpenSource.DB.Core;
using System.Data.Common;
using System.Security;
");
            
            #line default
            #line hidden
            
            #line 14 "DbConnectionFactoryTemplate.tt"

    foreach (var usingString in Usings)
    {

            
            #line default
            #line hidden
            
            #line 18 "DbConnectionFactoryTemplate.tt"
            this.Write("using ");
            
            #line default
            #line hidden
            
            #line 18 "DbConnectionFactoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( usingString ));
            
            #line default
            #line hidden
            
            #line 18 "DbConnectionFactoryTemplate.tt"
            this.Write(";\r\n");
            
            #line default
            #line hidden
            
            #line 19 "DbConnectionFactoryTemplate.tt"

    }

            
            #line default
            #line hidden
            
            #line 22 "DbConnectionFactoryTemplate.tt"
            this.Write("\r\n#nullable enable\r\n\r\nnamespace ");
            
            #line default
            #line hidden
            
            #line 25 "DbConnectionFactoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( BaseNamespace ));
            
            #line default
            #line hidden
            
            #line 25 "DbConnectionFactoryTemplate.tt"
            this.Write("\r\n{\r\n    public class ");
            
            #line default
            #line hidden
            
            #line 27 "DbConnectionFactoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( DatabasePrefix ));
            
            #line default
            #line hidden
            
            #line 27 "DbConnectionFactoryTemplate.tt"
            this.Write("ConnectionFactory : IDbConnectionFactory, IHostedLifecycleService\r\n    {\r\n       " +
                    " private readonly IConfiguration _Configuration;\r\n        private readonly strin" +
                    "g? _ServiceKey;\r\n\r\n        private readonly ILogger _Logger;\r\n        private re" +
                    "adonly string? _ConnectionString;\r\n        public PostgresqlConnectionFactory(IL" +
                    "ogger<PostgresqlConnectionFactory> logger, IConfiguration configuration, [Servic" +
                    "eKey] object? key)\r\n        {\r\n            _Configuration = configuration;\r\n    " +
                    "        _ServiceKey = key as string;\r\n            _Logger = logger;\r\n\r\n         " +
                    "   var connStrings = _Configuration.GetRequiredSection(\"ConnectionStrings\");\r\n  " +
                    "          if (!string.IsNullOrEmpty(_ServiceKey))\r\n                connStrings =" +
                    " connStrings.GetSection(_ServiceKey);\r\n\r\n            var connectionString = conn" +
                    "Strings[\"Default\"];\r\n            if (connectionString == null)\r\n            {\r\n " +
                    "               if (key != null)\r\n                    logger.LogWarning($\"No defa" +
                    "ult connection string for database {key} was found!\");\r\n                else\r\n  " +
                    "                  logger.LogWarning(\"No default connection string was found!\");\r" +
                    "\n\r\n                return;\r\n            }\r\n\r\n            _ConnectionString = con" +
                    "nectionString;\r\n        }\r\n\r\n        public async Task<bool> EnsureDbExists()\r\n " +
                    "       {\r\n            if (_ConnectionString == null)\r\n            {\r\n           " +
                    "     string message = $\"Failed to ensure that the {_ServiceKey} database exists," +
                    " because no ConnectionString was provided!\";\r\n                _Logger.LogCritica" +
                    "l(message);\r\n                throw new InvalidDataException(message);\r\n         " +
                    "   }\r\n            if (_ServiceKey == null)\r\n            {\r\n                strin" +
                    "g message = \"No service key (database name) was provided to this connection fact" +
                    "ory instance. Unable to ensure that the database exist!\";\r\n                _Logg" +
                    "er.LogCritical(message);\r\n                throw new InvalidDataException(message" +
                    ");\r\n            }\r\n\r\n            // Connect to the default \'postgres\' database t" +
                    "o check/create the new database\r\n            var masterConnectionBuilder = new N" +
                    "pgsqlConnectionStringBuilder(_ConnectionString)\r\n            {\r\n                " +
                    "Database = \"postgres\"\r\n            };\r\n\r\n            bool databaseExists = false" +
                    ";\r\n\r\n            using (var connection = new NpgsqlConnection(masterConnectionBu" +
                    "ilder.ToString()))\r\n            {\r\n                await connection.OpenAsync();" +
                    "\r\n\r\n                using (var command = connection.CreateCommand())\r\n          " +
                    "      {\r\n                    command.CommandText = \"SELECT 1 FROM pg_database WH" +
                    "ERE datname = @databaseName\";\r\n                    command.Parameters.Add(new Np" +
                    "gsqlParameter(\"databaseName\", _ServiceKey));\r\n                    \r\n            " +
                    "        var result = await global::Socigy.OpenSource.DB.Core.Diagnostics.DbDiagn" +
                    "ostics.ExecuteScalarAsync(command, \"DDL\", ct => command.ExecuteScalarAsync(ct));" +
                    "\r\n                    databaseExists = result != null;\r\n                }\r\n\r\n   " +
                    "             if (!databaseExists)\r\n                {\r\n                    using " +
                    "(var command = connection.CreateCommand())\r\n                    {\r\n             " +
                    "           command.CommandText = $\"CREATE DATABASE \\\"{_ServiceKey}\\\"\";\r\n        " +
                    "                await global::Socigy.OpenSource.DB.Core.Diagnostics.DbDiagnostic" +
                    "s.ExecuteNonQueryAsync(command, \"DDL\", ct => command.ExecuteNonQueryAsync(ct));\r" +
                    "\n                    }\r\n                }\r\n            }\r\n\r\n            return d" +
                    "atabaseExists;\r\n        }\r\n\r\n        private string? GetConnectionString(string " +
                    "key)\r\n        {\r\n            var connStrings = _Configuration.GetRequiredSection" +
                    "(\"ConnectionStrings\");\r\n            if (!string.IsNullOrEmpty(_ServiceKey))\r\n   " +
                    "             connStrings = connStrings.GetSection(_ServiceKey);\r\n\r\n            r" +
                    "eturn connStrings[key];\r\n        }\r\n\r\n        public DbConnection Create(string?" +
                    " connectionKey = null)\r\n        {\r\n            string? connectionString = null;\r" +
                    "\n            if (connectionKey != null)\r\n                connectionString = GetC" +
                    "onnectionString(connectionKey);\r\n\r\n            connectionString ??= _ConnectionS" +
                    "tring ?? throw new InvalidDataException(\"Unable to create DbConnection without a" +
                    " ConnectionString. Please provide a connection string and try again!\");\r\n\r\n     " +
                    "       // Connecting to the correct database\r\n            connectionString = con" +
                    "nectionString.TrimEnd().TrimEnd(\';\') + $\";Database={_ServiceKey}\";\r\n\r\n          " +
                    "  return new NpgsqlConnection(connectionString);\r\n        }\r\n\r\n        public as" +
                    "ync Task StartAsync(CancellationToken cancellationToken)\r\n        {\r\n           " +
                    " if (_ServiceKey != null && _ConnectionString != null)\r\n                await En" +
                    "sureDbExists();\r\n        }\r\n\r\n        #region HostedLifeCycle\r\n        public as" +
                    "ync Task StartedAsync(CancellationToken cancellationToken)\r\n        {\r\n        }" +
                    "\r\n        public async Task StartingAsync(CancellationToken cancellationToken)\r\n" +
                    "        {\r\n\r\n        }\r\n        public async Task StoppedAsync(CancellationToken" +
                    " cancellationToken)\r\n        {\r\n        }\r\n        public async Task StoppingAsy" +
                    "nc(CancellationToken cancellationToken)\r\n        {\r\n        }\r\n        public as" +
                    "ync Task StopAsync(CancellationToken cancellationToken)\r\n        {\r\n        }\r\n " +
                    "       #endregion\r\n    }\r\n}\r\n\r\n#nullable disable\r\n\r\n");
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        public virtual void Initialize() {
        }
    }
    
    public class DbConnectionFactoryTemplateBase {
        
        private global::System.Text.StringBuilder builder;
        
        private global::System.Collections.Generic.IDictionary<string, object> session;
        
        private global::System.CodeDom.Compiler.CompilerErrorCollection errors;
        
        private string currentIndent = string.Empty;
        
        private global::System.Collections.Generic.Stack<int> indents;
        
        private ToStringInstanceHelper _toStringHelper = new ToStringInstanceHelper();
        
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session {
            get {
                return this.session;
            }
            set {
                this.session = value;
            }
        }
        
        public global::System.Text.StringBuilder GenerationEnvironment {
            get {
                if ((this.builder == null)) {
                    this.builder = new global::System.Text.StringBuilder();
                }
                return this.builder;
            }
            set {
                this.builder = value;
            }
        }
        
        protected global::System.CodeDom.Compiler.CompilerErrorCollection Errors {
            get {
                if ((this.errors == null)) {
                    this.errors = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errors;
            }
        }
        
        public string CurrentIndent {
            get {
                return this.currentIndent;
            }
        }
        
        private global::System.Collections.Generic.Stack<int> Indents {
            get {
                if ((this.indents == null)) {
                    this.indents = new global::System.Collections.Generic.Stack<int>();
                }
                return this.indents;
            }
        }
        
        public ToStringInstanceHelper ToStringHelper {
            get {
                return this._toStringHelper;
            }
        }
        
        public void Error(string message) {
            this.Errors.Add(new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message));
        }
        
        public void Warning(string message) {
            global::System.CodeDom.Compiler.CompilerError val = new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message);
            val.IsWarning = true;
            this.Errors.Add(val);
        }
        
        public string PopIndent() {
            if ((this.Indents.Count == 0)) {
                return string.Empty;
            }
            int lastPos = (this.currentIndent.Length - this.Indents.Pop());
            string last = this.currentIndent.Substring(lastPos);
            this.currentIndent = this.currentIndent.Substring(0, lastPos);
            return last;
        }
        
        public void PushIndent(string indent) {
            this.Indents.Push(indent.Length);
            this.currentIndent = (this.currentIndent + indent);
        }
        
        public void ClearIndent() {
            this.currentIndent = string.Empty;
            this.Indents.Clear();
        }
        
        public void Write(string textToAppend) {
            this.GenerationEnvironment.Append(textToAppend);
        }
        
        public void Write(string format, params object[] args) {
            this.GenerationEnvironment.AppendFormat(format, args);
        }
        
        public void WriteLine(string textToAppend) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendLine(textToAppend);
        }
        
        public void WriteLine(string format, params object[] args) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendFormat(format, args);
            this.GenerationEnvironment.AppendLine();
        }
        
        public class ToStringInstanceHelper {
            
            private global::System.IFormatProvider formatProvider = global::System.Globalization.CultureInfo.InvariantCulture;
            
            public global::System.IFormatProvider FormatProvider {
                get {
                    return this.formatProvider;
                }
                set {
                    if ((value != null)) {
                        this.formatProvider = value;
                    }
                }
            }
            
            public string ToStringWithCulture(object objectToConvert) {
                if ((objectToConvert == null)) {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                global::System.Type type = objectToConvert.GetType();
                global::System.Type iConvertibleType = typeof(global::System.IConvertible);
                if (iConvertibleType.IsAssignableFrom(type)) {
                    return ((global::System.IConvertible)(objectToConvert)).ToString(this.formatProvider);
                }
                global::System.Reflection.MethodInfo methInfo = type.GetMethod("ToString", new global::System.Type[] {
                            iConvertibleType});
                if ((methInfo != null)) {
                    return ((string)(methInfo.Invoke(objectToConvert, new object[] {
                                this.formatProvider})));
                }
                return objectToConvert.ToString();
            }
        }
    }
}
