//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Socigy.OpenSource.DB.SourceGenerator.Templates {
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    
    public partial class MigrationManagerTemplate : MigrationManagerTemplateBase {
        
        
        #line 322 "MigrationManagerTemplate.tt"

    public string DatabaseName { get; set; }
    // Raw databaseName: the DI keyed-service key the MigrationManager resolves its connection factory under
    // (kept separate from DatabaseName, the C# type-name base).
    public string ServiceKey { get; set; }
    public string BaseNamespace { get; set; }
    public IList<string> MigrationClassNames { get; set; } = [];

        #line default
        #line hidden
        
        
        public virtual string TransformText() {
            this.GenerationEnvironment = null;
            
            #line 6 "MigrationManagerTemplate.tt"
            this.Write("#pragma warning disable\nusing Microsoft.Extensions.DependencyInjection;\nusing Mic" +
                    "rosoft.Extensions.Logging;\nusing Socigy.OpenSource.DB.Core.Migrations;\nusing Soc" +
                    "igy.OpenSource.DB.Core;\nusing Socigy.OpenSource.DB.Migrations;\n\n#nullable enable" +
                    "\n\nnamespace ");
            
            #line default
            #line hidden
            
            #line 15 "MigrationManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( BaseNamespace ));
            
            #line default
            #line hidden
            
            #line 15 "MigrationManagerTemplate.tt"
            this.Write("\n{\n    public static partial class ");
            
            #line default
            #line hidden
            
            #line 17 "MigrationManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( DatabaseName ));
            
            #line default
            #line hidden
            
            #line 17 "MigrationManagerTemplate.tt"
            this.Write(@"
    {
        public class MigrationManager : IMigrationManager
        {
            // Factories: only instantiate a migration when actually needed.
            // Migration SQL strings (UpSql/DownSql) can be large; this keeps them
            // out of memory until a migration is about to be applied, and GC can
            // collect them immediately after.
            // Declaration order here is irrelevant — the real apply order is resolved at class init by
            // following the PreviousId chain, which is robust to non-sortable / same-minute ids.
            private static readonly Func<ILocalMigration>[] _allFactories =
            [
    ");
            
            #line default
            #line hidden
            
            #line 29 "MigrationManagerTemplate.tt"

                foreach (var migrationName in MigrationClassNames)
                {
    
            
            #line default
            #line hidden
            
            #line 33 "MigrationManagerTemplate.tt"
            this.Write("          static () => new ");
            
            #line default
            #line hidden
            
            #line 33 "MigrationManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( migrationName ));
            
            #line default
            #line hidden
            
            #line 33 "MigrationManagerTemplate.tt"
            this.Write("(),\n    ");
            
            #line default
            #line hidden
            
            #line 34 "MigrationManagerTemplate.tt"

                }
    
            
            #line default
            #line hidden
            
            #line 37 "MigrationManagerTemplate.tt"
            this.Write("            ];\n\n            // Newest-first after chain resolution, with the matc" +
                    "hing id list and id->index map.\n            private static readonly Func<ILocalM" +
                    "igration>[] _factoriesOrderedDesc;\n            private static readonly string[] " +
                    "_idsOrderedDesc;\n            private static readonly Dictionary<string, int> _id" +
                    "ToIndex;\n\n            static MigrationManager()\n            {\n                va" +
                    "r byId = new Dictionary<string, Func<ILocalMigration>>(_allFactories.Length);\n  " +
                    "              var chain = new List<(string, string?)>(_allFactories.Length);\n   " +
                    "             foreach (var factory in _allFactories)\n                {\n          " +
                    "          var migration = factory();\n                    byId[migration.Id] = fa" +
                    "ctory;\n                    chain.Add((migration.Id, migration.PreviousId));\n    " +
                    "            }\n\n                // Oldest -> newest by PreviousId chain; throws l" +
                    "oudly on a broken/forked chain.\n                var ascending = global::Socigy.O" +
                    "penSource.DB.Core.Migrations.MigrationHistory.OrderByChain(chain);\n             " +
                    "   int count = ascending.Count;\n                _factoriesOrderedDesc = new Func" +
                    "<ILocalMigration>[count];\n                _idsOrderedDesc = new string[count];\n " +
                    "               _idToIndex = new Dictionary<string, int>(count);\n                " +
                    "for (int i = 0; i < count; i++)\n                {\n                    var id = a" +
                    "scending[count - 1 - i]; // newest first\n                    _factoriesOrderedDe" +
                    "sc[i] = byId[id];\n                    _idsOrderedDesc[i] = id;\n                 " +
                    "   _idToIndex[id] = i;\n                }\n            }\n\n            // IMigratio" +
                    "nManager.LocalMigrations — materialises on demand (rarely called).\n            p" +
                    "ublic Dictionary<string, ILocalMigration> LocalMigrations =>\n                _id" +
                    "ToIndex.ToDictionary(kvp => kvp.Key, kvp => _factoriesOrderedDesc[kvp.Value]());" +
                    "\n\n            private readonly ILogger _Logger;\n            private readonly IDb" +
                    "ConnectionFactory _ConnectionFactory;\n            public MigrationManager(ILogge" +
                    "r<MigrationManager> logger, [FromKeyedServices(\"");
            
            #line default
            #line hidden
            
            #line 76 "MigrationManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( ServiceKey ));
            
            #line default
            #line hidden
            
            #line 76 "MigrationManagerTemplate.tt"
            this.Write("\")] IDbConnectionFactory connectionFactory)\n            {\n                _Logger" +
                    " = logger;\n                _ConnectionFactory = connectionFactory;\n            }" +
                    "\n\n            public Task EnsureLatestVersion()\n            {\n                if" +
                    " (_idsOrderedDesc.Length == 0) return Task.CompletedTask;\n                if (!_" +
                    "idToIndex.TryGetValue(_idsOrderedDesc[0], out int idx))\n                    thro" +
                    "w new InvalidOperationException(\"Latest migration not found in index.\");\n       " +
                    "         return EnsureMigration(_factoriesOrderedDesc[idx]());\n            }\n\n  " +
                    "          public Task EnsureMigration(string migrationId)\n            {\n        " +
                    "        if (!_idToIndex.TryGetValue(migrationId, out int idx))\n                 " +
                    "   throw new MissingMemberException($\"Missing local migration with ID {migration" +
                    "Id}\");\n                return EnsureMigration(_factoriesOrderedDesc[idx]());\n   " +
                    "         }\n\n            public async Task EnsureMigration(ILocalMigration migrat" +
                    "ion)\n            {\n                await _ConnectionFactory.EnsureDbExists();\n\n " +
                    "               if (!_idToIndex.TryGetValue(migration.Id, out int targetMigration" +
                    "Index))\n                    throw new InvalidDataException($\"Target migration {m" +
                    "igration.Id} not found locally.\");\n\n                using var connection = _Conn" +
                    "ectionFactory.Create();\n                await connection.OpenAsync();\n\n         " +
                    "       // Serialize migration apply across every process/replica. Each replica c" +
                    "alls\n                // EnsureLatest{Db}Migration() on startup; without this loc" +
                    "k they race the same CREATE TABLE /\n                // DDL and crash with 42P07 " +
                    "/ 42701 / 23505, or half-apply schema. pg_advisory_lock is\n                // se" +
                    "ssion-scoped on this connection and auto-releases if the process dies, so a cras" +
                    "hed\n                // migrator can\'t deadlock the fleet. ReadAppliedSet (below," +
                    " under the lock) makes a waiter\n                // that acquires the lock after " +
                    "the winner skip everything the winner already applied.\n                static lo" +
                    "ng __AdvisoryKey(string s)\n                {\n                    unchecked\n     " +
                    "               {\n                        // Deterministic FNV-1a 64-bit. string." +
                    "GetHashCode is randomized per-process, so it\n                        // would gi" +
                    "ve each replica a different key and defeat the lock.\n                        ulo" +
                    "ng h = 1469598103934665603UL;\n                        foreach (char c in s) { h " +
                    "^= c; h *= 1099511628211UL; }\n                        return (long)h;\n          " +
                    "          }\n                }\n                long __migrationLockKey = __Adviso" +
                    "ryKey(\"socigy.migrations:\" + \"");
            
            #line default
            #line hidden
            
            #line 124 "MigrationManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( ServiceKey ));
            
            #line default
            #line hidden
            
            #line 124 "MigrationManagerTemplate.tt"
            this.Write(@""");
                using (var __lockCmd = connection.CreateCommand())
                {
                    __lockCmd.CommandText = ""SELECT pg_advisory_lock("" + __migrationLockKey.ToString(System.Globalization.CultureInfo.InvariantCulture) + "")"";
                    await __lockCmd.ExecuteNonQueryAsync();
                }
                try
                {
                // Read the current version UNDER the advisory lock. Doing it before the lock let the
                // source==target short-circuit (and the apply/rollback direction) race a concurrent apply/rollback
                // on another replica: this process could read ""already at target"" and return while another replica
                // was mid-rollback, leaving the schema behind with no self-correction. The cost is that an
                // already-current startup now briefly takes the lock too — negligible, and correct.
                var dbVersion = await GetCurrentMigrationVersion();
                int sourceMigrationIndex;
                if (dbVersion == null)
                    sourceMigrationIndex = _idsOrderedDesc.Length;
                else if (!_idToIndex.TryGetValue(dbVersion.HumanId, out sourceMigrationIndex))
                    throw new InvalidDataException($""Unable to find local migration with ID {dbVersion.HumanId} that is in the Database. Aborting!"");

                if (sourceMigrationIndex == targetMigrationIndex)
                {
                    _Logger.LogInformation($""");
            
            #line default
            #line hidden
            
            #line 146 "MigrationManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( DatabaseName ));
            
            #line default
            #line hidden
            
            #line 146 "MigrationManagerTemplate.tt"
            this.Write(" is already at version: {migration.Id}\");\n                    return;\n           " +
                    "     }\n\n                if (sourceMigrationIndex > targetMigrationIndex)\n       " +
                    "         {\n                    // Defensive: never re-run UP DDL for a migration" +
                    " that is currently applied,\n                    // even if version resolution ab" +
                    "ove returned null for some reason. The set is\n                    // rollback-aw" +
                    "are (a DOWN nets the migration back out), so an UP -> DOWN -> UP\n               " +
                    "     // is correctly re-applied rather than skipped.\n                    var app" +
                    "lied = await ReadAppliedSet();\n                    for (int i = sourceMigrationI" +
                    "ndex - 1; i >= targetMigrationIndex; i--)\n                    {\n                " +
                    "        // Instantiate only for the duration of this loop body\n                 " +
                    "       var migToApply = _factoriesOrderedDesc[i]();\n                        if (" +
                    "applied.Contains(migToApply.Id))\n                        {\n                     " +
                    "       _Logger.LogInformation($\"Skipping already-applied UP migration: {migToApp" +
                    "ly.Id}\");\n                            continue;\n                        }\n      " +
                    "                  _Logger.LogInformation($\"Applying UP migration: {migToApply.Id" +
                    "} - {migToApply.GetType().Name}\");\n\n                        // The schema change" +
                    " and its version row commit together or roll back together.\n                    " +
                    "    await global::Socigy.OpenSource.DB.Core.Migrations.MigrationExecutor.ApplyAt" +
                    "omicAsync(\n                            connection,\n                            m" +
                    "igToApply.UpSql,\n                            tx => ");
            
            #line default
            #line hidden
            
            #line 172 "MigrationManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( DatabaseName ));
            
            #line default
            #line hidden
            
            #line 172 "MigrationManagerTemplate.tt"
            this.Write(".Migration.InsertAsync(new ");
            
            #line default
            #line hidden
            
            #line 172 "MigrationManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( DatabaseName ));
            
            #line default
            #line hidden
            
            #line 172 "MigrationManagerTemplate.tt"
            this.Write(".Migration\n                            {\n                                HumanId " +
                    "= migToApply.Id,\n                                AppliedAt = DateTime.UtcNow,\n  " +
                    "                              ExecutedBy = $\"{Environment.UserName} - {Environme" +
                    "nt.MachineName}\",\n                                IsRollback = false\n           " +
                    "                 }, connection, tx));\n                        // migToApply goes" +
                    " out of scope here — SQL strings are GC-eligible\n                    }\n         " +
                    "       }\n                else\n                {\n                    // Mirror th" +
                    "e UP guard: only roll back migrations that are CURRENTLY applied. sourceMigratio" +
                    "nIndex\n                    // was computed before the advisory lock, so a concur" +
                    "rent (or already-completed) rollback could\n                    // otherwise re-r" +
                    "un DownSql for a migration that is no longer applied, failing on the missing\n   " +
                    "                 // object or recording a duplicate rollback row. The set is rol" +
                    "lback-aware.\n                    var applied = await ReadAppliedSet();\n         " +
                    "           for (int i = sourceMigrationIndex; i < targetMigrationIndex; i++)\n   " +
                    "                 {\n                        var migToApply = _factoriesOrderedDes" +
                    "c[i]();\n                        if (!applied.Contains(migToApply.Id))\n          " +
                    "              {\n                            _Logger.LogInformation($\"Skipping al" +
                    "ready-rolled-back DOWN migration: {migToApply.Id}\");\n                           " +
                    " continue;\n                        }\n                        _Logger.LogInformat" +
                    "ion($\"Applying DOWN migration: {migToApply.Id} - {migToApply.GetType().Name}\");\n" +
                    "\n                        // The schema change and its version row commit togethe" +
                    "r or roll back together.\n                        await global::Socigy.OpenSource" +
                    ".DB.Core.Migrations.MigrationExecutor.ApplyAtomicAsync(\n                        " +
                    "    connection,\n                            migToApply.DownSql,\n                " +
                    "            tx => ");
            
            #line default
            #line hidden
            
            #line 203 "MigrationManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( DatabaseName ));
            
            #line default
            #line hidden
            
            #line 203 "MigrationManagerTemplate.tt"
            this.Write(".Migration.InsertAsync(new ");
            
            #line default
            #line hidden
            
            #line 203 "MigrationManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( DatabaseName ));
            
            #line default
            #line hidden
            
            #line 203 "MigrationManagerTemplate.tt"
            this.Write(".Migration\n                            {\n                                HumanId " +
                    "= migToApply.Id,\n                                AppliedAt = DateTime.UtcNow,\n  " +
                    "                              ExecutedBy = $\"{Environment.UserName} - {Environme" +
                    "nt.MachineName}\",\n                                IsRollback = true\n            " +
                    "                }, connection, tx));\n                    }\n                }\n   " +
                    "             }\n                finally\n                {\n                    usi" +
                    "ng var __unlockCmd = connection.CreateCommand();\n                    __unlockCmd" +
                    ".CommandText = \"SELECT pg_advisory_unlock(\" + __migrationLockKey.ToString(System" +
                    ".Globalization.CultureInfo.InvariantCulture) + \")\";\n                    await __" +
                    "unlockCmd.ExecuteNonQueryAsync();\n                }\n            }\n\n            p" +
                    "ublic async Task<ILocalMigration?> GetCurrentLocalMigrationVersion()\n           " +
                    " {\n                var latestVersion = await GetCurrentMigrationVersion();\n     " +
                    "           if (latestVersion == null || !_idToIndex.TryGetValue(latestVersion.Hu" +
                    "manId, out int idx))\n                    return null;\n                return _fa" +
                    "ctoriesOrderedDesc[idx]();\n            }\n\n            public async Task<IMigrati" +
                    "on?> GetCurrentMigrationVersion()\n            {\n                try\n            " +
                    "    {\n                    using var connection = _ConnectionFactory.Create();\n  " +
                    "                  if (connection.State != System.Data.ConnectionState.Open)\n    " +
                    "                    await connection.OpenAsync();\n\n                    // On fir" +
                    "st run the migrations table doesn\'t exist yet. Probe with to_regclass,\n         " +
                    "           // wrapped in \"IS NOT NULL\" so Npgsql materialises a boolean: reading" +
                    " the raw\n                    // regclass value as object throws InvalidCastExcep" +
                    "tion once the table exists,\n                    // which previously got swallowe" +
                    "d below and re-ran every UP migration on restart.\n                    using (var" +
                    " probe = connection.CreateCommand())\n                    {\n                     " +
                    "   probe.CommandText = \"SELECT to_regclass(\'\\\"\" + ");
            
            #line default
            #line hidden
            
            #line 243 "MigrationManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( DatabaseName ));
            
            #line default
            #line hidden
            
            #line 243 "MigrationManagerTemplate.tt"
            this.Write(@".Migration.TableName + ""\""') IS NOT NULL"";
                        var exists = await probe.ExecuteScalarAsync();
                        if (!(exists is bool b && b))
                            return null;
                    }

                    // Read the full history and resolve the current version accounting for rollbacks: a DOWN
                    // migration records an IsRollback row, so simply taking the latest row by timestamp would
                    // report a rolled-back migration as still current.
                    var rows = new System.Collections.Generic.List<");
            
            #line default
            #line hidden
            
            #line 252 "MigrationManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( DatabaseName ));
            
            #line default
            #line hidden
            
            #line 252 "MigrationManagerTemplate.tt"
            this.Write(".Migration>();\n                    await foreach (var row in ");
            
            #line default
            #line hidden
            
            #line 253 "MigrationManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( DatabaseName ));
            
            #line default
            #line hidden
            
            #line 253 "MigrationManagerTemplate.tt"
            this.Write(@".Migration.Query().WithConnection(connection).ExecuteAsync())
                        rows.Add(row);

                    var records = new System.Collections.Generic.List<(long, string, System.DateTime, bool)>(rows.Count);
                    foreach (var row in rows)
                        records.Add((row.Id, row.HumanId, row.AppliedAt, row.IsRollback));

                    var currentId = global::Socigy.OpenSource.DB.Core.Migrations.MigrationHistory.ResolveCurrentVersion(records);
                    if (currentId == null)
                        return null;

                    // Pick the most recently applied row for that id by the monotonic Id (true apply order), not AppliedAt.
                    ");
            
            #line default
            #line hidden
            
            #line 265 "MigrationManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( DatabaseName ));
            
            #line default
            #line hidden
            
            #line 265 "MigrationManagerTemplate.tt"
            this.Write(@".Migration? current = null;
                    foreach (var row in rows)
                        if (row.HumanId == currentId && !row.IsRollback && (current == null || row.Id >= current.Id))
                            current = row;
                    return current;
                }
                catch (Exception ex)
                {
                    // Never swallow a read failure into null: that path is read as ""nothing applied""
                    // by EnsureMigration and triggers a destructive re-apply of already-applied DDL.
                    _Logger.LogError(ex,
                        ""Failed to read current migration version from {Table}. Refusing to treat this as an empty database."",
                        ");
            
            #line default
            #line hidden
            
            #line 277 "MigrationManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( DatabaseName ));
            
            #line default
            #line hidden
            
            #line 277 "MigrationManagerTemplate.tt"
            this.Write(@".Migration.TableName);
                    throw;
                }
            }

            // Reads the rollback-aware set of currently-applied migration ids using a plain command
            // over only the columns we need, deliberately bypassing the row-materialisation query path
            // so this guard stays usable even if that path regresses. Empty set means table absent.
            private async Task<System.Collections.Generic.HashSet<string>> ReadAppliedSet()
            {
                using var connection = _ConnectionFactory.Create();
                if (connection.State != System.Data.ConnectionState.Open)
                    await connection.OpenAsync();

                using (var probe = connection.CreateCommand())
                {
                    probe.CommandText = ""SELECT to_regclass('\"""" + ");
            
            #line default
            #line hidden
            
            #line 293 "MigrationManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( DatabaseName ));
            
            #line default
            #line hidden
            
            #line 293 "MigrationManagerTemplate.tt"
            this.Write(@".Migration.TableName + ""\""') IS NOT NULL"";
                    var exists = await probe.ExecuteScalarAsync();
                    if (!(exists is bool b && b))
                        return new System.Collections.Generic.HashSet<string>();
                }

                var records = new System.Collections.Generic.List<(long, string, System.DateTime, bool)>();
                using (var cmd = connection.CreateCommand())
                {
                    cmd.CommandText =
                        ""SELECT \"""" + ");
            
            #line default
            #line hidden
            
            #line 303 "MigrationManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( DatabaseName ));
            
            #line default
            #line hidden
            
            #line 303 "MigrationManagerTemplate.tt"
            this.Write(".Migration.IdColumnName + \"\\\", \\\"\" +\n                        ");
            
            #line default
            #line hidden
            
            #line 304 "MigrationManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( DatabaseName ));
            
            #line default
            #line hidden
            
            #line 304 "MigrationManagerTemplate.tt"
            this.Write(".Migration.HumanIdColumnName + \"\\\", \\\"\" +\n                        ");
            
            #line default
            #line hidden
            
            #line 305 "MigrationManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( DatabaseName ));
            
            #line default
            #line hidden
            
            #line 305 "MigrationManagerTemplate.tt"
            this.Write(".Migration.AppliedAtColumnName + \"\\\", \\\"\" +\n                        ");
            
            #line default
            #line hidden
            
            #line 306 "MigrationManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( DatabaseName ));
            
            #line default
            #line hidden
            
            #line 306 "MigrationManagerTemplate.tt"
            this.Write(".Migration.IsRollbackColumnName + \"\\\" FROM \\\"\" +\n                        ");
            
            #line default
            #line hidden
            
            #line 307 "MigrationManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( DatabaseName ));
            
            #line default
            #line hidden
            
            #line 307 "MigrationManagerTemplate.tt"
            this.Write(@".Migration.TableName + ""\"""";

                    await using var instr = await global::Socigy.OpenSource.DB.Core.Diagnostics.DbDiagnostics.ExecuteReaderAsync(
                        cmd, ""SELECT"", ct => cmd.ExecuteReaderAsync(ct));
                    while (await instr.ReadAsync())
                        records.Add((instr.Reader.GetInt64(0), instr.Reader.GetString(1), instr.Reader.GetDateTime(2), instr.Reader.GetBoolean(3)));
                }

                return global::Socigy.OpenSource.DB.Core.Migrations.MigrationHistory.ResolveAppliedSet(records);
            }
        }
    }
}

#nullable disable
");
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        public virtual void Initialize() {
        }
    }
    
    public class MigrationManagerTemplateBase {
        
        private global::System.Text.StringBuilder builder;
        
        private global::System.Collections.Generic.IDictionary<string, object> session;
        
        private global::System.CodeDom.Compiler.CompilerErrorCollection errors;
        
        private string currentIndent = string.Empty;
        
        private global::System.Collections.Generic.Stack<int> indents;
        
        private ToStringInstanceHelper _toStringHelper = new ToStringInstanceHelper();
        
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session {
            get {
                return this.session;
            }
            set {
                this.session = value;
            }
        }
        
        public global::System.Text.StringBuilder GenerationEnvironment {
            get {
                if ((this.builder == null)) {
                    this.builder = new global::System.Text.StringBuilder();
                }
                return this.builder;
            }
            set {
                this.builder = value;
            }
        }
        
        protected global::System.CodeDom.Compiler.CompilerErrorCollection Errors {
            get {
                if ((this.errors == null)) {
                    this.errors = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errors;
            }
        }
        
        public string CurrentIndent {
            get {
                return this.currentIndent;
            }
        }
        
        private global::System.Collections.Generic.Stack<int> Indents {
            get {
                if ((this.indents == null)) {
                    this.indents = new global::System.Collections.Generic.Stack<int>();
                }
                return this.indents;
            }
        }
        
        public ToStringInstanceHelper ToStringHelper {
            get {
                return this._toStringHelper;
            }
        }
        
        public void Error(string message) {
            this.Errors.Add(new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message));
        }
        
        public void Warning(string message) {
            global::System.CodeDom.Compiler.CompilerError val = new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message);
            val.IsWarning = true;
            this.Errors.Add(val);
        }
        
        public string PopIndent() {
            if ((this.Indents.Count == 0)) {
                return string.Empty;
            }
            int lastPos = (this.currentIndent.Length - this.Indents.Pop());
            string last = this.currentIndent.Substring(lastPos);
            this.currentIndent = this.currentIndent.Substring(0, lastPos);
            return last;
        }
        
        public void PushIndent(string indent) {
            this.Indents.Push(indent.Length);
            this.currentIndent = (this.currentIndent + indent);
        }
        
        public void ClearIndent() {
            this.currentIndent = string.Empty;
            this.Indents.Clear();
        }
        
        public void Write(string textToAppend) {
            this.GenerationEnvironment.Append(textToAppend);
        }
        
        public void Write(string format, params object[] args) {
            this.GenerationEnvironment.AppendFormat(format, args);
        }
        
        public void WriteLine(string textToAppend) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendLine(textToAppend);
        }
        
        public void WriteLine(string format, params object[] args) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendFormat(format, args);
            this.GenerationEnvironment.AppendLine();
        }
        
        public class ToStringInstanceHelper {
            
            private global::System.IFormatProvider formatProvider = global::System.Globalization.CultureInfo.InvariantCulture;
            
            public global::System.IFormatProvider FormatProvider {
                get {
                    return this.formatProvider;
                }
                set {
                    if ((value != null)) {
                        this.formatProvider = value;
                    }
                }
            }
            
            public string ToStringWithCulture(object objectToConvert) {
                if ((objectToConvert == null)) {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                global::System.Type type = objectToConvert.GetType();
                global::System.Type iConvertibleType = typeof(global::System.IConvertible);
                if (iConvertibleType.IsAssignableFrom(type)) {
                    return ((global::System.IConvertible)(objectToConvert)).ToString(this.formatProvider);
                }
                global::System.Reflection.MethodInfo methInfo = type.GetMethod("ToString", new global::System.Type[] {
                            iConvertibleType});
                if ((methInfo != null)) {
                    return ((string)(methInfo.Invoke(objectToConvert, new object[] {
                                this.formatProvider})));
                }
                return objectToConvert.ToString();
            }
        }
    }
}
