// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Socigy.OpenSource.DB.SourceGenerator.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;

    /// <summary>
    /// Class to produce the template output
    /// </summary>

    #line 1 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableColumnNameClassTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class TableColumnNameClassTemplate : TableColumnNameClassTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("#pragma warning disable\n\n\n\n\nusing Socigy.OpenSource.DB.Core.Interfaces;\nusing System.Collections.Generic" +
                    ";\nusing Socigy.OpenSource.DB.Core.CommandBuilders;\nusing System;\n\n#nullable enabl" +
                    "e\n\nnamespace ");

            #line 1 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));

            #line default
            #line hidden
            this.Write(" \n{\n    \n    ");

            #line 1 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CustomPreClass));

            #line default
            #line hidden
            this.Write("\n    public partial class ");

            #line 1 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));

            #line default
            #line hidden
            this.Write(@" : IDbTable
    {
        protected Dictionary<string, object?> _CustomValues { get; set; }
        public object? GetCustomValue(string key)
        {
            if (_CustomValues == null)
                return null;

            return _CustomValues.ContainsKey(key) ? _CustomValues[key] : null;
        }
        public T? GetCustomValue<T>(string key)
        {
            if (_CustomValues == null)
                return default(T);

            return _CustomValues.ContainsKey(key) ? (T?)_CustomValues[key] : default;
        }

        public const string TableName = """);

            #line 1 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));

            #line default
            #line hidden
            this.Write("\";\n        public string GetTableName() => TableName;\n\n        public static stri" +
                    "ng? GetColumnDbName(string column)\n        {\n            return column switch\n  " +
                    "          {\n");

            #line 1 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableColumnNameClassTemplate.tt"

            foreach(var col in Columns)
            {


            #line default
            #line hidden
            this.Write("\n                \"");

            #line 1 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));

            #line default
            #line hidden
            this.Write("\" => ");

            #line 1 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));

            #line default
            #line hidden
            this.Write("ColumnName,\n");

            #line 1 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableColumnNameClassTemplate.tt"

            }


            #line default
            #line hidden
            this.Write("\n                _ => null\n            };\n        }\n\n        string? IDbTable.GetD" +
                    "bColumnName(string memberName) => GetColumnDbName(memberName);\n\n        public " +
                    "Dictionary<string, ColumnInfo> GetColumns()\n        {\n            return new Di" +
                    "ctionary<string, ColumnInfo>()\n            {\n");

            #line 1 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableColumnNameClassTemplate.tt"

                foreach(var col in Columns)
                {
                    bool isTypedJson = col.IsJsonColumn && !string.IsNullOrEmpty(col.JsonContextType);


            #line default
            #line hidden
            this.Write("              {\n                    ");

            #line 1 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));

            #line default
            #line hidden
            this.Write("ColumnName,\n                    new ColumnInfo()\n                    {\n          " +
                    "              Type = typeof(");

            #line 1 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.IsJsonColumn ? "string " : col.Type.Replace("?", " ")));

            #line default
            #line hidden
            this.Write("),\n                        Value = ");

            #line 1 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableColumnNameClassTemplate.tt"
            if (isTypedJson)
            {
                this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
                this.Write(" == null ? null : global::System.Text.Json.JsonSerializer.Serialize(");
                this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
                this.Write(", ");
                this.Write(this.ToStringHelper.ToStringWithCulture(col.JsonContextType));
                this.Write(".Default.Options)");
            }
            else
            {
                this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            }

            #line default
            #line hidden
            this.Write(",\n                        IsJson = ");

            #line 1 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.IsJsonColumn ? "true" : "false"));

            #line default
            #line hidden
            this.Write(",\n                        IsPrimaryKey = ");

            #line 1 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.IsPrimaryKey ? "true" : "false"));

            #line default
            #line hidden
            this.Write(",\n                        IsAutoIncrement = ");

            #line 1 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.IsAutoIncrement ? "true" : "false"));

            #line default
            #line hidden
            this.Write(",\n                        HasDbDefault = ");

            #line 1 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.HasDbDefault ? "true" : "false"));

            #line default
            #line hidden
            this.Write(",\n                        SetValue = ");

            #line 1 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableColumnNameClassTemplate.tt"
            if (isTypedJson)
            {
                this.Write("v => ");
                this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
                this.Write(" = v == null || v is DBNull ? null : global::System.Text.Json.JsonSerializer.Deserialize<");
                this.Write(this.ToStringHelper.ToStringWithCulture(col.Type.TrimEnd('?')));
                this.Write(">(v?.ToString() ?? \"\", ");
                this.Write(this.ToStringHelper.ToStringWithCulture(col.JsonContextType));
                this.Write(".Default.Options)");
            }
            else
            {
                this.Write("v => ");
                this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
                this.Write(" = ColumnInfo.ApplyDbValue<");
                this.Write(this.ToStringHelper.ToStringWithCulture(col.Type));
                this.Write(">(v)");
            }

            #line default
            #line hidden
            this.Write("\n                    }\n                },\n");

            #line 1 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableColumnNameClassTemplate.tt"

                }


            #line default
            #line hidden
            this.Write("\n            };\n        }\n\n        public Dictionary<string, ColumnInfo> GetPrima" +
                    "ryColumns()\n        {\n            return new Dictionary<string, ColumnInfo>()\n  " +
                    "          {\n");

            #line 1 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableColumnNameClassTemplate.tt"

             foreach(var col in Columns.Where(x => x.IsPrimaryKey))
             {


            #line default
            #line hidden
            this.Write("              {\n                    ");

            #line 1 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));

            #line default
            #line hidden
            this.Write("ColumnName,\n                    new ColumnInfo()\n                    {\n          " +
                    "              Type = typeof(");

            #line 1 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Type.Replace("?", " ")));

            #line default
            #line hidden
            this.Write("),\n                        Value = ");

            #line 1 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));

            #line default
            #line hidden
            this.Write(",\n                        IsPrimaryKey = true,\n                        IsAutoIncrement = ");

            #line 1 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.IsAutoIncrement ? "true" : "false"));

            #line default
            #line hidden
            this.Write(",\n                        HasDbDefault = ");

            #line 1 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.HasDbDefault ? "true" : "false"));

            #line default
            #line hidden
            this.Write(",\n                        SetValue = v => ");

            #line 1 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));

            #line default
            #line hidden
            this.Write(" = ColumnInfo.ApplyDbValue<");

            #line 1 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Type));

            #line default
            #line hidden
            this.Write(">(v)\n                    }\n                },\n");

            #line 1 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableColumnNameClassTemplate.tt"

                }


            #line default
            #line hidden
            this.Write("\n            };\n        }\n\n        public (string Name, ColumnInfo Info)? GetColu" +
                    "mn(string name)\n        {\n            switch(name)\n            {\n");

            #line 1 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableColumnNameClassTemplate.tt"

               foreach (var col in Columns)
               {
                   bool isTypedJson = col.IsJsonColumn && !string.IsNullOrEmpty(col.JsonContextType);


            #line default
            #line hidden
            this.Write("\n                case ");

            #line 1 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));

            #line default
            #line hidden
            this.Write("ColumnName:\n                    return (\n                        ");

            #line 1 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));

            #line default
            #line hidden
            this.Write("ColumnName,\n                        new ColumnInfo()\n                        {\n  " +
                    "                          Type = typeof(");

            #line 1 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.IsJsonColumn ? "string " : col.Type.Replace("?", " ")));

            #line default
            #line hidden
            this.Write("),\n                            Value = ");

            #line 1 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableColumnNameClassTemplate.tt"
            if (isTypedJson)
            {
                this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
                this.Write(" == null ? null : global::System.Text.Json.JsonSerializer.Serialize(");
                this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
                this.Write(", ");
                this.Write(this.ToStringHelper.ToStringWithCulture(col.JsonContextType));
                this.Write(".Default.Options)");
            }
            else
            {
                this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            }

            #line default
            #line hidden
            this.Write(",\n                            IsJson = ");

            #line 1 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.IsJsonColumn ? "true" : "false"));

            #line default
            #line hidden
            this.Write(",\n                            IsPrimaryKey = ");

            #line 1 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.IsPrimaryKey ? "true" : "false"));

            #line default
            #line hidden
            this.Write(",\n                            IsAutoIncrement = ");

            #line 1 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.IsAutoIncrement ? "true" : "false"));

            #line default
            #line hidden
            this.Write(",\n                            HasDbDefault = ");

            #line 1 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.HasDbDefault ? "true" : "false"));

            #line default
            #line hidden
            this.Write(",\n                            SetValue = ");

            #line 1 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableColumnNameClassTemplate.tt"
            if (isTypedJson)
            {
                this.Write("v => ");
                this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
                this.Write(" = v == null || v is DBNull ? null : global::System.Text.Json.JsonSerializer.Deserialize<");
                this.Write(this.ToStringHelper.ToStringWithCulture(col.Type.TrimEnd('?')));
                this.Write(">(v?.ToString() ?? \"\", ");
                this.Write(this.ToStringHelper.ToStringWithCulture(col.JsonContextType));
                this.Write(".Default.Options)");
            }
            else
            {
                this.Write("v => ");
                this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
                this.Write(" = ColumnInfo.ApplyDbValue<");
                this.Write(this.ToStringHelper.ToStringWithCulture(col.Type));
                this.Write(">(v)");
            }

            #line default
            #line hidden
            this.Write("\n                        }\n                    );\n");

            #line 1 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableColumnNameClassTemplate.tt"

               }


            #line default
            #line hidden
            this.Write("\n            }\n            \n            return null;\n        }\n");

            #line 1 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableColumnNameClassTemplate.tt"

        foreach(var col in Columns)
        {


            #line default
            #line hidden
            this.Write("\n        public const string ");

            #line 1 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));

            #line default
            #line hidden
            this.Write("ColumnName = \"");

            #line 1 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.DatabaseName));

            #line default
            #line hidden
            this.Write("\";\n");

            #line 1 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableColumnNameClassTemplate.tt"

        }


            #line default
            #line hidden
            this.Write("\n    }\n    ");

            #line 1 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CustomPostClass));

            #line default
            #line hidden
            this.Write("\n}\n\n#nullable disable\n\n");
            return this.GenerationEnvironment.ToString();
        }

        #line 1 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableColumnNameClassTemplate.tt"

    public string ClassName { get; set; }
    public string TableName { get; set; }
    public string Namespace { get; set; }
    public List<ColumnInfo> Columns { get; set; }

    public string CustomPreClass { get; set; } = "";
    public string CustomPostClass { get; set; } = "";

    public class ColumnInfo
    {
        public string Name { get; set; }
        public string Type { get; set; }
        public string DatabaseName { get; set; }
        public bool IsPrimaryKey { get; set; }
        public bool IsAutoIncrement { get; set; }
        public bool HasDbDefault { get; set; }
        public string SequenceName { get; set; }
        public bool IsJsonColumn { get; set; }
        public string JsonContextType { get; set; }
    }


        #line default
        #line hidden
    }

    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public class TableColumnNameClassTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                return this.generationEnvironmentField;
            }
            set { this.generationEnvironmentField = value; }
        }
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                return this.errorsField;
            }
        }
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                return this.indentLengthsField;
            }
        }
        public string CurrentIndent { get { return this.currentIndentField; } }
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get { return this.sessionField; }
            set { this.sessionField = value; }
        }
        #endregion
        #region Transform-time helpers
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend)) return;
            if (((this.GenerationEnvironment.Length == 0) || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
                this.endsWithNewline = true;
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            if (this.endsWithNewline)
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            else
                this.GenerationEnvironment.Append(textToAppend);
        }
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        public void Write(string format, params object[] args) { this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args)); }
        public void WriteLine(string format, params object[] args) { this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args)); }
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        public void PushIndent(string indent)
        {
            if ((indent == null)) throw new global::System.ArgumentNullException("indent");
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        public void ClearIndent() { this.indentLengths.Clear(); this.currentIndentField = ""; }
        #endregion
        #region ToString Helpers
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField = global::System.Globalization.CultureInfo.InvariantCulture;
            public System.IFormatProvider FormatProvider
            {
                get { return this.formatProviderField; }
                set { if ((value != null)) this.formatProviderField = value; }
            }
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null)) throw new global::System.ArgumentNullException("objectToConvert");
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] { typeof(System.IFormatProvider) });
                if ((method == null)) return objectToConvert.ToString();
                else return ((string)(method.Invoke(objectToConvert, new object[] { this.formatProviderField })));
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        public ToStringInstanceHelper ToStringHelper { get { return this.toStringHelperField; } }
        #endregion
    }
    #endregion
}
