//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Socigy.OpenSource.DB.SourceGenerator.Templates {
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    
    public partial class TableColumnNameClassTemplate : TableColumnNameClassTemplateBase {
        
        
        #line 243 "TableColumnNameClassTemplate.tt"

    public string ClassName { get; set; }
    public string TableName { get; set; }
    public string Namespace { get; set; }
    public List<ColumnInfo> Columns { get; set; }

    public string CustomPreClass { get; set; } = "";
    public string CustomPostClass { get; set; } = "";

    public class ColumnInfo
    {
        public string Name { get; set; }
        public string Type { get; set; }
        public string DatabaseName { get; set; }
        public bool IsPrimaryKey { get; set; }
        public bool IsAutoIncrement { get; set; }
        public bool HasDbDefault { get; set; }
        public string SequenceName { get; set; }
        public bool IsJsonColumn { get; set; }
        public string JsonContextType { get; set; }
        public string Converter { get; set; }
        public bool IsEncrypted { get; set; }
        public bool EncryptAutoDecrypt { get; set; } = true;
    }

    // Shared emit helpers for GetInsertPlan(bool) so the default and include-all plans stay identical.
    string InsertColList(System.Collections.Generic.IEnumerable<ColumnInfo> cols)
        => string.Join(", ", cols.Select(c => "\\\"" + c.DatabaseName + "\\\""));
    string InsertParamList(System.Collections.Generic.IEnumerable<ColumnInfo> cols)
        => string.Join(", ", cols.Select(c => "@" + c.DatabaseName));
    void EmitInsertDescriptors(System.Collections.Generic.IEnumerable<ColumnInfo> cols)
    {
        foreach (var col in cols)
        {
            bool isTypedJson = col.IsJsonColumn && !string.IsNullOrEmpty(col.JsonContextType);
            bool hasConvertor = !col.IsJsonColumn && !string.IsNullOrEmpty(col.Converter);
            string encType = col.Type.Replace("?", "");
            string typeExpr = col.IsEncrypted ? "byte[]" : (col.IsJsonColumn ? "string " : col.Type.Replace("?", " "));
            string valueExpr = col.IsEncrypted
                ? "global::Socigy.OpenSource.DB.Core.Encryption.FieldCrypto.Encrypt((object?)((" + ClassName + ")o)." + col.Name + ", typeof(" + encType + "), TableName + \":\" + " + col.Name + "ColumnName)"
                : isTypedJson
                    ? "((" + ClassName + ")o)." + col.Name + " == null ? (object?)null : global::System.Text.Json.JsonSerializer.Serialize(((" + ClassName + ")o)." + col.Name + ", " + col.JsonContextType + ".Default.Options)"
                : hasConvertor
                    ? "new " + col.Converter + "().ConvertToDbValue(((" + ClassName + ")o)." + col.Name + ")"
                : "(object?)((" + ClassName + ")o)." + col.Name;
            WriteLine("                    new global::Socigy.OpenSource.DB.Core.CommandBuilders.InsertColumnDescriptor(\"@" + col.DatabaseName + "\", typeof(" + typeExpr + "), " + (col.IsJsonColumn ? "true" : "false") + ", o => " + valueExpr + ", " + (col.IsEncrypted ? "true" : "false") + "),");
        }
    }

        #line default
        #line hidden
        
        
        public virtual string TransformText() {
            this.GenerationEnvironment = null;
            
            #line 6 "TableColumnNameClassTemplate.tt"
            this.Write("#pragma warning disable\r\nusing Socigy.OpenSource.DB.Core.Interfaces;\r\nusing Syste" +
                    "m.Collections.Generic;\r\nusing Socigy.OpenSource.DB.Core.CommandBuilders;\r\n\r\n#nul" +
                    "lable enable\r\n\r\nnamespace ");
            
            #line default
            #line hidden
            
            #line 13 "TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Namespace ));
            
            #line default
            #line hidden
            
            #line 13 "TableColumnNameClassTemplate.tt"
            this.Write("\r\n{\r\n\r\n    ");
            
            #line default
            #line hidden
            
            #line 16 "TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( CustomPreClass ));
            
            #line default
            #line hidden
            
            #line 16 "TableColumnNameClassTemplate.tt"
            this.Write("\r\n    public partial class ");
            
            #line default
            #line hidden
            
            #line 17 "TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( ClassName ));
            
            #line default
            #line hidden
            
            #line 17 "TableColumnNameClassTemplate.tt"
            this.Write(" : IDbTable, IInsertPlanProvider, IOrdinalReadable\r\n    {\r\n        protected Dict" +
                    "ionary<string, object?> _CustomValues { get; set; }\r\n        public object? GetC" +
                    "ustomValue(string key)\r\n        {\r\n            if (_CustomValues == null)\r\n     " +
                    "           return null;\r\n\r\n            return _CustomValues.ContainsKey(key) ? _" +
                    "CustomValues[key] : null;\r\n        }\r\n        public T? GetCustomValue<T>(string" +
                    " key)\r\n        {\r\n            if (_CustomValues == null)\r\n                return" +
                    " default(T);\r\n\r\n            return _CustomValues.ContainsKey(key) ? (T?)_CustomV" +
                    "alues[key] : default;\r\n        }\r\n\r\n        /// <summary>Stores a value for a cu" +
                    "stom (undeclared) column — used by DynamicTable&lt;T&gt; auto-mapping.</summary>" +
                    "\r\n        public void SetCustomValue(string key, object? value)\r\n        {\r\n    " +
                    "        _CustomValues ??= new Dictionary<string, object?>();\r\n            _Custo" +
                    "mValues[key] = value;\r\n        }\r\n\r\n        /// <summary>Reads a captured custom" +
                    " (undeclared) column value, converting if needed; false when absent.</summary>\r\n" +
                    "        public bool TryGetCustomValue<TValue>(string key, out TValue? value)\r\n  " +
                    "      {\r\n            if (_CustomValues != null && _CustomValues.TryGetValue(key," +
                    " out var __raw))\r\n            {\r\n                if (__raw == null || __raw is S" +
                    "ystem.DBNull) { value = default; return true; }\r\n                if (__raw is TV" +
                    "alue __typed) { value = __typed; return true; }\r\n                try\r\n          " +
                    "      {\r\n                    var __t = System.Nullable.GetUnderlyingType(typeof(" +
                    "TValue)) ?? typeof(TValue);\r\n                    value = (TValue)System.Convert." +
                    "ChangeType(__raw, __t);\r\n                    return true;\r\n                }\r\n  " +
                    "              catch { value = default; return false; }\r\n            }\r\n         " +
                    "   value = default;\r\n            return false;\r\n        }\r\n\r\n        public cons" +
                    "t string TableName = \"");
            
            #line default
            #line hidden
            
            #line 61 "TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( TableName ));
            
            #line default
            #line hidden
            
            #line 61 "TableColumnNameClassTemplate.tt"
            this.Write("\";\r\n        public string GetTableName() => TableName;\r\n\r\n        public static s" +
                    "tring? GetColumnDbName(string column)\r\n        {\r\n            return column swit" +
                    "ch\r\n            {\r\n");
            
            #line default
            #line hidden
            
            #line 68 "TableColumnNameClassTemplate.tt"

            foreach(var col in Columns)
            {
                if (col.IsEncrypted)
                {

            
            #line default
            #line hidden
            
            #line 74 "TableColumnNameClassTemplate.tt"
            this.Write("                \"");
            
            #line default
            #line hidden
            
            #line 74 "TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( col.Name ));
            
            #line default
            #line hidden
            
            #line 74 "TableColumnNameClassTemplate.tt"
            this.Write("\" => throw new global::System.NotSupportedException(\"Column \'");
            
            #line default
            #line hidden
            
            #line 74 "TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( col.Name ));
            
            #line default
            #line hidden
            
            #line 74 "TableColumnNameClassTemplate.tt"
            this.Write("\' is [Encrypted] and cannot be used in a WHERE / ORDER BY / SELECT-projection / L" +
                    "IKE clause — encryption is non-deterministic. Filter by a non-encrypted key inst" +
                    "ead.\"),\r\n");
            
            #line default
            #line hidden
            
            #line 75 "TableColumnNameClassTemplate.tt"

                }
                else
                {

            
            #line default
            #line hidden
            
            #line 80 "TableColumnNameClassTemplate.tt"
            this.Write("                \"");
            
            #line default
            #line hidden
            
            #line 80 "TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( col.Name ));
            
            #line default
            #line hidden
            
            #line 80 "TableColumnNameClassTemplate.tt"
            this.Write("\" => ");
            
            #line default
            #line hidden
            
            #line 80 "TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( col.Name ));
            
            #line default
            #line hidden
            
            #line 80 "TableColumnNameClassTemplate.tt"
            this.Write("ColumnName,\r\n");
            
            #line default
            #line hidden
            
            #line 81 "TableColumnNameClassTemplate.tt"

                }
            }
        
            
            #line default
            #line hidden
            
            #line 85 "TableColumnNameClassTemplate.tt"
            this.Write(@"                _ => null
            };
        }

        string? IDbTable.GetDbColumnName(string memberName) => GetColumnDbName(memberName);

        public Dictionary<string, ColumnInfo> GetColumns()
        {
            return new Dictionary<string, ColumnInfo>()
            {
");
            
            #line default
            #line hidden
            
            #line 95 "TableColumnNameClassTemplate.tt"

                foreach(var col in Columns)
                {
                    bool isTypedJson = col.IsJsonColumn && !string.IsNullOrEmpty(col.JsonContextType);
                    bool hasConvertor = !col.IsJsonColumn && !string.IsNullOrEmpty(col.Converter);
                    string encType = col.Type.Replace("?", "");
                    string typeExpr = col.IsEncrypted ? "byte[]" : (col.IsJsonColumn ? "string " : col.Type.Replace("?", " "));
                    string valueExpr = col.IsEncrypted
                        ? "global::Socigy.OpenSource.DB.Core.Encryption.FieldCrypto.Encrypt((object?)" + col.Name + ", typeof(" + encType + "), TableName + \":\" + " + col.Name + "ColumnName)"
                        : isTypedJson ? col.Name + " == null ? null : global::System.Text.Json.JsonSerializer.Serialize(" + col.Name + ", " + col.JsonContextType + ".Default.Options)"
                        : hasConvertor ? "new " + col.Converter + "().ConvertToDbValue(" + col.Name + ")"
                        : col.Name;
                    string setExpr = col.IsEncrypted
                        ? (col.EncryptAutoDecrypt
                            ? "v => " + col.Name + " = (" + col.Type + ")(global::Socigy.OpenSource.DB.Core.Encryption.FieldCrypto.Decrypt(v, typeof(" + encType + "), TableName + \":\" + " + col.Name + "ColumnName) ?? default(" + col.Type + "))"
                            : "v => { " + col.Name + "RawEncrypted = v as byte[]; _" + col.Name + "Decrypted = false; }")
                        : isTypedJson ? "v => " + col.Name + " = v == null || v is DBNull ? null : global::System.Text.Json.JsonSerializer.Deserialize<" + col.Type.TrimEnd('?') + ">(v?.ToString() ?? \"\", " + col.JsonContextType + ".Default.Options)"
                        : hasConvertor ? "v => " + col.Name + " = (" + col.Type + ")(new " + col.Converter + "().ConvertFromDbValue(v))"
                        : "v => " + col.Name + " = ColumnInfo.ApplyDbValue<" + col.Type + ">(v)";

            
            #line default
            #line hidden
            
            #line 115 "TableColumnNameClassTemplate.tt"
            this.Write("              {\r\n                    ");
            
            #line default
            #line hidden
            
            #line 116 "TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( col.Name ));
            
            #line default
            #line hidden
            
            #line 116 "TableColumnNameClassTemplate.tt"
            this.Write("ColumnName,\r\n                    new ColumnInfo()\r\n                    {\r\n       " +
                    "                 Type = typeof(");
            
            #line default
            #line hidden
            
            #line 119 "TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( typeExpr ));
            
            #line default
            #line hidden
            
            #line 119 "TableColumnNameClassTemplate.tt"
            this.Write("),\r\n                        Value = ");
            
            #line default
            #line hidden
            
            #line 120 "TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( valueExpr ));
            
            #line default
            #line hidden
            
            #line 120 "TableColumnNameClassTemplate.tt"
            this.Write(",\r\n                        IsJson = ");
            
            #line default
            #line hidden
            
            #line 121 "TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( col.IsJsonColumn ? "true" : "false" ));
            
            #line default
            #line hidden
            
            #line 121 "TableColumnNameClassTemplate.tt"
            this.Write(",\r\n                        IsEncrypted = ");
            
            #line default
            #line hidden
            
            #line 122 "TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( col.IsEncrypted ? "true" : "false" ));
            
            #line default
            #line hidden
            
            #line 122 "TableColumnNameClassTemplate.tt"
            this.Write(",\r\n                        IsPrimaryKey = ");
            
            #line default
            #line hidden
            
            #line 123 "TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( col.IsPrimaryKey ? "true" : "false" ));
            
            #line default
            #line hidden
            
            #line 123 "TableColumnNameClassTemplate.tt"
            this.Write(",\r\n                        IsAutoIncrement = ");
            
            #line default
            #line hidden
            
            #line 124 "TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( col.IsAutoIncrement ? "true" : "false" ));
            
            #line default
            #line hidden
            
            #line 124 "TableColumnNameClassTemplate.tt"
            this.Write(",\r\n                        HasDbDefault = ");
            
            #line default
            #line hidden
            
            #line 125 "TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( col.HasDbDefault ? "true" : "false" ));
            
            #line default
            #line hidden
            
            #line 125 "TableColumnNameClassTemplate.tt"
            this.Write(",\r\n                        SetValue = ");
            
            #line default
            #line hidden
            
            #line 126 "TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( setExpr ));
            
            #line default
            #line hidden
            
            #line 126 "TableColumnNameClassTemplate.tt"
            this.Write("\r\n                    }\r\n                },\r\n");
            
            #line default
            #line hidden
            
            #line 129 "TableColumnNameClassTemplate.tt"

                }

            
            #line default
            #line hidden
            
            #line 132 "TableColumnNameClassTemplate.tt"
            this.Write(@"            };
        }

        private static global::Socigy.OpenSource.DB.Core.CommandBuilders.InsertPlan? __InsertPlan;
        private static global::Socigy.OpenSource.DB.Core.CommandBuilders.InsertPlan? __InsertPlanAll;
        /// <summary>Cached plan for the default INSERT (all columns except auto-increment), reused per call.</summary>
        public global::Socigy.OpenSource.DB.Core.CommandBuilders.InsertPlan GetInsertPlan() => GetInsertPlan(false);
        /// <summary>Cached INSERT plan; pass <c>true</c> to also include auto-increment columns (supply your own values).</summary>
        public global::Socigy.OpenSource.DB.Core.CommandBuilders.InsertPlan GetInsertPlan(bool includeAutoIncrement)
        {
            if (includeAutoIncrement)
                return __InsertPlanAll ??= new global::Socigy.OpenSource.DB.Core.CommandBuilders.InsertPlan(
                    ""INSERT INTO \""");
            
            #line default
            #line hidden
            
            #line 144 "TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( TableName ));
            
            #line default
            #line hidden
            
            #line 144 "TableColumnNameClassTemplate.tt"
            this.Write("\\\" (");
            
            #line default
            #line hidden
            
            #line 144 "TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( InsertColList(Columns) ));
            
            #line default
            #line hidden
            
            #line 144 "TableColumnNameClassTemplate.tt"
            this.Write(") VALUES (");
            
            #line default
            #line hidden
            
            #line 144 "TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( InsertParamList(Columns) ));
            
            #line default
            #line hidden
            
            #line 144 "TableColumnNameClassTemplate.tt"
            this.Write(")\",\r\n                    new global::Socigy.OpenSource.DB.Core.CommandBuilders.In" +
                    "sertColumnDescriptor[]\r\n                    {\r\n");
            
            #line default
            #line hidden
            
            #line 147 "TableColumnNameClassTemplate.tt"
 EmitInsertDescriptors(Columns); 
            
            #line default
            #line hidden
            
            #line 148 "TableColumnNameClassTemplate.tt"
            this.Write("                    });\r\n            return __InsertPlan ??= new global::Socigy.O" +
                    "penSource.DB.Core.CommandBuilders.InsertPlan(\r\n                \"INSERT INTO \\\"");
            
            #line default
            #line hidden
            
            #line 150 "TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( TableName ));
            
            #line default
            #line hidden
            
            #line 150 "TableColumnNameClassTemplate.tt"
            this.Write("\\\" (");
            
            #line default
            #line hidden
            
            #line 150 "TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( InsertColList(Columns.Where(c => !c.IsAutoIncrement)) ));
            
            #line default
            #line hidden
            
            #line 150 "TableColumnNameClassTemplate.tt"
            this.Write(") VALUES (");
            
            #line default
            #line hidden
            
            #line 150 "TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( InsertParamList(Columns.Where(c => !c.IsAutoIncrement)) ));
            
            #line default
            #line hidden
            
            #line 150 "TableColumnNameClassTemplate.tt"
            this.Write(")\",\r\n                new global::Socigy.OpenSource.DB.Core.CommandBuilders.Insert" +
                    "ColumnDescriptor[]\r\n                {\r\n");
            
            #line default
            #line hidden
            
            #line 153 "TableColumnNameClassTemplate.tt"
 EmitInsertDescriptors(Columns.Where(c => !c.IsAutoIncrement)); 
            
            #line default
            #line hidden
            
            #line 154 "TableColumnNameClassTemplate.tt"
            this.Write("                });\r\n        }\r\n\r\n        public Dictionary<string, ColumnInfo> G" +
                    "etPrimaryColumns()\r\n        {\r\n            return new Dictionary<string, ColumnI" +
                    "nfo>()\r\n            {\r\n");
            
            #line default
            #line hidden
            
            #line 161 "TableColumnNameClassTemplate.tt"

             foreach(var col in Columns.Where(x => x.IsPrimaryKey))
             {

            
            #line default
            #line hidden
            
            #line 165 "TableColumnNameClassTemplate.tt"
            this.Write("              {\r\n                    ");
            
            #line default
            #line hidden
            
            #line 166 "TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( col.Name ));
            
            #line default
            #line hidden
            
            #line 166 "TableColumnNameClassTemplate.tt"
            this.Write("ColumnName,\r\n                    new ColumnInfo()\r\n                    {\r\n       " +
                    "                 Type = typeof(");
            
            #line default
            #line hidden
            
            #line 169 "TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( col.Type.Replace("?", " ") ));
            
            #line default
            #line hidden
            
            #line 169 "TableColumnNameClassTemplate.tt"
            this.Write("),\r\n                        Value = ");
            
            #line default
            #line hidden
            
            #line 170 "TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( col.Name ));
            
            #line default
            #line hidden
            
            #line 170 "TableColumnNameClassTemplate.tt"
            this.Write(",\r\n                        IsPrimaryKey = true,\r\n                        IsAutoIn" +
                    "crement = ");
            
            #line default
            #line hidden
            
            #line 172 "TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( col.IsAutoIncrement ? "true" : "false" ));
            
            #line default
            #line hidden
            
            #line 172 "TableColumnNameClassTemplate.tt"
            this.Write(",\r\n                        HasDbDefault = ");
            
            #line default
            #line hidden
            
            #line 173 "TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( col.HasDbDefault ? "true" : "false" ));
            
            #line default
            #line hidden
            
            #line 173 "TableColumnNameClassTemplate.tt"
            this.Write(",\r\n                        SetValue = v => ");
            
            #line default
            #line hidden
            
            #line 174 "TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( col.Name ));
            
            #line default
            #line hidden
            
            #line 174 "TableColumnNameClassTemplate.tt"
            this.Write(" = ColumnInfo.ApplyDbValue<");
            
            #line default
            #line hidden
            
            #line 174 "TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( col.Type ));
            
            #line default
            #line hidden
            
            #line 174 "TableColumnNameClassTemplate.tt"
            this.Write(">(v)\r\n                    }\r\n                },\r\n");
            
            #line default
            #line hidden
            
            #line 177 "TableColumnNameClassTemplate.tt"

                }

            
            #line default
            #line hidden
            
            #line 180 "TableColumnNameClassTemplate.tt"
            this.Write("            };\r\n        }\r\n\r\n        public (string Name, ColumnInfo Info)? GetCo" +
                    "lumn(string name)\r\n        {\r\n            switch(name)\r\n            {\r\n");
            
            #line default
            #line hidden
            
            #line 187 "TableColumnNameClassTemplate.tt"

               foreach (var col in Columns)
               {
                   bool isTypedJson = col.IsJsonColumn && !string.IsNullOrEmpty(col.JsonContextType);
                   bool hasConvertor = !col.IsJsonColumn && !string.IsNullOrEmpty(col.Converter);
                   string encType = col.Type.Replace("?", "");
                   string typeExpr = col.IsEncrypted ? "byte[]" : (col.IsJsonColumn ? "string " : col.Type.Replace("?", " "));
                   string valueExpr = col.IsEncrypted
                       ? "global::Socigy.OpenSource.DB.Core.Encryption.FieldCrypto.Encrypt((object?)" + col.Name + ", typeof(" + encType + "), TableName + \":\" + " + col.Name + "ColumnName)"
                       : isTypedJson ? col.Name + " == null ? null : global::System.Text.Json.JsonSerializer.Serialize(" + col.Name + ", " + col.JsonContextType + ".Default.Options)"
                       : hasConvertor ? "new " + col.Converter + "().ConvertToDbValue(" + col.Name + ")"
                       : col.Name;
                   string setExpr = col.IsEncrypted
                       ? (col.EncryptAutoDecrypt
                           ? "v => " + col.Name + " = (" + col.Type + ")(global::Socigy.OpenSource.DB.Core.Encryption.FieldCrypto.Decrypt(v, typeof(" + encType + "), TableName + \":\" + " + col.Name + "ColumnName) ?? default(" + col.Type + "))"
                           : "v => { " + col.Name + "RawEncrypted = v as byte[]; _" + col.Name + "Decrypted = false; }")
                       : isTypedJson ? "v => " + col.Name + " = v == null || v is DBNull ? null : global::System.Text.Json.JsonSerializer.Deserialize<" + col.Type.TrimEnd('?') + ">(v?.ToString() ?? \"\", " + col.JsonContextType + ".Default.Options)"
                       : hasConvertor ? "v => " + col.Name + " = (" + col.Type + ")(new " + col.Converter + "().ConvertFromDbValue(v))"
                       : "v => " + col.Name + " = ColumnInfo.ApplyDbValue<" + col.Type + ">(v)";

            
            #line default
            #line hidden
            
            #line 207 "TableColumnNameClassTemplate.tt"
            this.Write("                case ");
            
            #line default
            #line hidden
            
            #line 207 "TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( col.Name ));
            
            #line default
            #line hidden
            
            #line 207 "TableColumnNameClassTemplate.tt"
            this.Write("ColumnName:\r\n                    return (\r\n                        ");
            
            #line default
            #line hidden
            
            #line 209 "TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( col.Name ));
            
            #line default
            #line hidden
            
            #line 209 "TableColumnNameClassTemplate.tt"
            this.Write("ColumnName,\r\n                        new ColumnInfo()\r\n                        {\r" +
                    "\n                            Type = typeof(");
            
            #line default
            #line hidden
            
            #line 212 "TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( typeExpr ));
            
            #line default
            #line hidden
            
            #line 212 "TableColumnNameClassTemplate.tt"
            this.Write("),\r\n                            Value = ");
            
            #line default
            #line hidden
            
            #line 213 "TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( valueExpr ));
            
            #line default
            #line hidden
            
            #line 213 "TableColumnNameClassTemplate.tt"
            this.Write(",\r\n                            IsJson = ");
            
            #line default
            #line hidden
            
            #line 214 "TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( col.IsJsonColumn ? "true" : "false" ));
            
            #line default
            #line hidden
            
            #line 214 "TableColumnNameClassTemplate.tt"
            this.Write(",\r\n                            IsEncrypted = ");
            
            #line default
            #line hidden
            
            #line 215 "TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( col.IsEncrypted ? "true" : "false" ));
            
            #line default
            #line hidden
            
            #line 215 "TableColumnNameClassTemplate.tt"
            this.Write(",\r\n                            IsPrimaryKey = ");
            
            #line default
            #line hidden
            
            #line 216 "TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( col.IsPrimaryKey ? "true" : "false" ));
            
            #line default
            #line hidden
            
            #line 216 "TableColumnNameClassTemplate.tt"
            this.Write(",\r\n                            IsAutoIncrement = ");
            
            #line default
            #line hidden
            
            #line 217 "TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( col.IsAutoIncrement ? "true" : "false" ));
            
            #line default
            #line hidden
            
            #line 217 "TableColumnNameClassTemplate.tt"
            this.Write(",\r\n                            HasDbDefault = ");
            
            #line default
            #line hidden
            
            #line 218 "TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( col.HasDbDefault ? "true" : "false" ));
            
            #line default
            #line hidden
            
            #line 218 "TableColumnNameClassTemplate.tt"
            this.Write(",\r\n                            SetValue = ");
            
            #line default
            #line hidden
            
            #line 219 "TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( setExpr ));
            
            #line default
            #line hidden
            
            #line 219 "TableColumnNameClassTemplate.tt"
            this.Write("\r\n                        }\r\n                    );\r\n");
            
            #line default
            #line hidden
            
            #line 222 "TableColumnNameClassTemplate.tt"

               }

            
            #line default
            #line hidden
            
            #line 225 "TableColumnNameClassTemplate.tt"
            this.Write("            }\r\n\r\n            return null;\r\n        }\r\n");
            
            #line default
            #line hidden
            
            #line 229 "TableColumnNameClassTemplate.tt"

        foreach(var col in Columns)
        {
        
            
            #line default
            #line hidden
            
            #line 233 "TableColumnNameClassTemplate.tt"
            this.Write("        public const string ");
            
            #line default
            #line hidden
            
            #line 233 "TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( col.Name ));
            
            #line default
            #line hidden
            
            #line 233 "TableColumnNameClassTemplate.tt"
            this.Write("ColumnName = \"");
            
            #line default
            #line hidden
            
            #line 233 "TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( col.DatabaseName ));
            
            #line default
            #line hidden
            
            #line 233 "TableColumnNameClassTemplate.tt"
            this.Write("\";\r\n");
            
            #line default
            #line hidden
            
            #line 234 "TableColumnNameClassTemplate.tt"

        }
        
            
            #line default
            #line hidden
            
            #line 237 "TableColumnNameClassTemplate.tt"
            this.Write("    }\r\n    ");
            
            #line default
            #line hidden
            
            #line 238 "TableColumnNameClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( CustomPostClass ));
            
            #line default
            #line hidden
            
            #line 238 "TableColumnNameClassTemplate.tt"
            this.Write("\r\n}\r\n\r\n#nullable disable\r\n\r\n");
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        public virtual void Initialize() {
        }
    }
    
    public class TableColumnNameClassTemplateBase {
        
        private global::System.Text.StringBuilder builder;
        
        private global::System.Collections.Generic.IDictionary<string, object> session;
        
        private global::System.CodeDom.Compiler.CompilerErrorCollection errors;
        
        private string currentIndent = string.Empty;
        
        private global::System.Collections.Generic.Stack<int> indents;
        
        private ToStringInstanceHelper _toStringHelper = new ToStringInstanceHelper();
        
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session {
            get {
                return this.session;
            }
            set {
                this.session = value;
            }
        }
        
        public global::System.Text.StringBuilder GenerationEnvironment {
            get {
                if ((this.builder == null)) {
                    this.builder = new global::System.Text.StringBuilder();
                }
                return this.builder;
            }
            set {
                this.builder = value;
            }
        }
        
        protected global::System.CodeDom.Compiler.CompilerErrorCollection Errors {
            get {
                if ((this.errors == null)) {
                    this.errors = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errors;
            }
        }
        
        public string CurrentIndent {
            get {
                return this.currentIndent;
            }
        }
        
        private global::System.Collections.Generic.Stack<int> Indents {
            get {
                if ((this.indents == null)) {
                    this.indents = new global::System.Collections.Generic.Stack<int>();
                }
                return this.indents;
            }
        }
        
        public ToStringInstanceHelper ToStringHelper {
            get {
                return this._toStringHelper;
            }
        }
        
        public void Error(string message) {
            this.Errors.Add(new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message));
        }
        
        public void Warning(string message) {
            global::System.CodeDom.Compiler.CompilerError val = new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message);
            val.IsWarning = true;
            this.Errors.Add(val);
        }
        
        public string PopIndent() {
            if ((this.Indents.Count == 0)) {
                return string.Empty;
            }
            int lastPos = (this.currentIndent.Length - this.Indents.Pop());
            string last = this.currentIndent.Substring(lastPos);
            this.currentIndent = this.currentIndent.Substring(0, lastPos);
            return last;
        }
        
        public void PushIndent(string indent) {
            this.Indents.Push(indent.Length);
            this.currentIndent = (this.currentIndent + indent);
        }
        
        public void ClearIndent() {
            this.currentIndent = string.Empty;
            this.Indents.Clear();
        }
        
        public void Write(string textToAppend) {
            this.GenerationEnvironment.Append(textToAppend);
        }
        
        public void Write(string format, params object[] args) {
            this.GenerationEnvironment.AppendFormat(format, args);
        }
        
        public void WriteLine(string textToAppend) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendLine(textToAppend);
        }
        
        public void WriteLine(string format, params object[] args) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendFormat(format, args);
            this.GenerationEnvironment.AppendLine();
        }
        
        public class ToStringInstanceHelper {
            
            private global::System.IFormatProvider formatProvider = global::System.Globalization.CultureInfo.InvariantCulture;
            
            public global::System.IFormatProvider FormatProvider {
                get {
                    return this.formatProvider;
                }
                set {
                    if ((value != null)) {
                        this.formatProvider = value;
                    }
                }
            }
            
            public string ToStringWithCulture(object objectToConvert) {
                if ((objectToConvert == null)) {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                global::System.Type type = objectToConvert.GetType();
                global::System.Type iConvertibleType = typeof(global::System.IConvertible);
                if (iConvertibleType.IsAssignableFrom(type)) {
                    return ((global::System.IConvertible)(objectToConvert)).ToString(this.formatProvider);
                }
                global::System.Reflection.MethodInfo methInfo = type.GetMethod("ToString", new global::System.Type[] {
                            iConvertibleType});
                if ((methInfo != null)) {
                    return ((string)(methInfo.Invoke(objectToConvert, new object[] {
                                this.formatProvider})));
                }
                return objectToConvert.ToString();
            }
        }
    }
}
