using System;
using System.Linq;
using System.Threading.Tasks;
using Npgsql;
using NUnit.Framework;
using Socigy.OpenSource.DB.Attributes;
using Socigy.OpenSource.DB.Tool.Introspection;
using Socigy.OpenSource.DB.Tool.Structures.Analysis;

namespace Socigy.OpenSource.DB.Tool.Tests;

/// <summary>
/// Live-database coverage for <see cref="PostgresSchemaReader"/>: creates known tables and asserts the
/// introspection (types, nullability, varchar length, defaults, identity, primary/foreign keys) reconstructs
/// them — exercising the actual information_schema/pg_catalog queries and the inverse translators end to end.
/// Gated on a reachable PostgreSQL (env <c>SOCIGY_TEST_PG</c>, else the conventional local test DB); ignored
/// when none is available so it never breaks DB-less runs.
/// </summary>
[TestFixture]
public class PostgresSchemaReaderTests
{
    private static string ConnString()
        => Environment.GetEnvironmentVariable("SOCIGY_TEST_PG")
           ?? "Host=127.0.0.1;Port=5432;Username=postgres;Password=1234;Database=postgres";

    private static async Task<NpgsqlConnection?> TryOpenAsync()
    {
        try
        {
            var conn = new NpgsqlConnection(ConnString());
            await conn.OpenAsync();
            return conn;
        }
        catch
        {
            return null;
        }
    }

    private static async Task Exec(NpgsqlConnection conn, string sql)
    {
        await using var cmd = conn.CreateCommand();
        cmd.CommandText = sql;
        await cmd.ExecuteNonQueryAsync();
    }

    [Test]
    public async Task Reader_Reconstructs_Tables_Columns_Keys_Defaults_And_ForeignKeys()
    {
        var conn = await TryOpenAsync();
        if (conn is null)
        {
            Assert.Ignore("No reachable PostgreSQL (set SOCIGY_TEST_PG to enable this test).");
            return;
        }

        await using var _ = conn;
        const string schema = "socigy_reader_test";

        await Exec(conn, $@"DROP SCHEMA IF EXISTS ""{schema}"" CASCADE; CREATE SCHEMA ""{schema}"";");
        try
        {
            await Exec(conn, $@"
                CREATE TABLE ""{schema}"".""parent"" (
                    ""id""         uuid PRIMARY KEY,
                    ""name""       varchar(50) NOT NULL,
                    ""created_at"" timestamp without time zone DEFAULT timezone('utc', now())
                );
                CREATE TABLE ""{schema}"".""child"" (
                    ""id""        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""parent_id"" uuid NOT NULL REFERENCES ""{schema}"".""parent""(""id"") ON DELETE CASCADE,
                    ""note""      text
                );");

            DbSchema dbSchema = await PostgresSchemaReader.ReadAsync(ConnString(), schema);

            Assert.That(dbSchema.Tables.Select(t => t.Name), Is.EquivalentTo(new[] { "parent", "child" }));

            // ── parent: PK, type mapping, varchar length, NOT NULL, default inverse-translation ──
            var parent = dbSchema.Tables.Single(t => t.Name == "parent");
            Assert.That(parent.SourceName, Is.EqualTo("Parent"));

            var id = parent.Columns.Single(c => c.Name == "id");
            Assert.That(id.IsPrimaryKey, Is.True);
            Assert.That(id.DotnetType, Is.EqualTo("Guid"));

            var name = parent.Columns.Single(c => c.Name == "name");
            Assert.That(name.DotnetType, Is.EqualTo("string"));
            Assert.That(name.Nullable, Is.False);
            Assert.That(name.MaxLength, Is.EqualTo(50));

            var createdAt = parent.Columns.Single(c => c.Name == "created_at");
            Assert.That(createdAt.DotnetType, Is.EqualTo("DateTime"));
            Assert.That(createdAt.DefaultValue, Is.EqualTo(DbDefaults.Time.Now),
                "timezone('utc', now()) must inverse-translate to DbDefaults.Time.Now (cast stripping)");

            // ── child: identity → auto-increment, FK target + columns + ON DELETE action ──
            var child = dbSchema.Tables.Single(t => t.Name == "child");

            var childId = child.Columns.Single(c => c.Name == "id");
            Assert.That(childId.IsAutoIncrement, Is.True, "GENERATED ... AS IDENTITY must read as auto-increment");
            Assert.That(childId.DotnetType, Is.EqualTo("long"));

            var fk = child.Constraints.Single(c => c.Type == DbConstraint.Types.ForeignKey);
            Assert.That(fk.Columns, Is.EquivalentTo(new[] { "ParentId" }));
            Assert.That(fk.TargetTable, Is.EqualTo("Parent"));
            Assert.That(fk.TargetColumns, Is.EquivalentTo(new[] { "Id" }));
            Assert.That(fk.OnDelete, Is.EqualTo(DbValues.ForeignKey.Cascade));
        }
        finally
        {
            await Exec(conn, $@"DROP SCHEMA IF EXISTS ""{schema}"" CASCADE;");
        }
    }
}
