using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace Socigy.OpenSource.DB.SourceGenerator
{
    /// <summary>
    /// Emits the testable, interface-based database context layer:
    /// <list type="bullet">
    /// <item><c>I{Db}</c> + <c>{Db}Context</c> — the per-database facade exposing one table set per table.</item>
    /// <item><c>I{Table}Set</c> + <c>{Table}Set</c> — terminal CRUD + streaming methods mapped to the existing builders.</item>
    /// <item><c>{Db}Factory</c> — the <see cref="Socigy.OpenSource.DB.Core.Context.SocigyDatabaseFactoryBase{TDatabase}"/> subclass.</item>
    /// <item><c>Add{Db}Context</c> — DI registration wiring the factory, options and diagnostics.</item>
    /// </list>
    /// String-built (like <see cref="ProcedureGenerator"/>) rather than T4 to avoid template/regeneration coupling.
    /// </summary>
    public static class ContextGenerator
    {
        private const string TableAttributeFullName = "Socigy.OpenSource.DB.Attributes.TableAttribute";
        private const string FlagTableAttributeFullName = "Socigy.OpenSource.DB.Attributes.FlagTableAttribute";

        private readonly struct TableRef
        {
            public TableRef(string className, string ns) { ClassName = className; Namespace = ns; }
            public string ClassName { get; }
            public string Namespace { get; }
            public string FullName => string.IsNullOrEmpty(Namespace) ? ClassName : Namespace + "." + ClassName;
        }

        public static void Execute(SourceProductionContext ctx, Compilation compilation, ImmutableArray<ClassDeclarationSyntax> tables, Program program)
        {
            // Only generate when a database is configured (mirrors ExtensionGenerator).
            if (string.IsNullOrWhiteSpace(program.DatabasePrefix))
                return;

            string db = program.Settings?.Database?.DatabaseName ?? "UnnamedDb";

            var refs = new List<TableRef>();
            foreach (var table in tables)
            {
                var model = compilation.GetSemanticModel(table.SyntaxTree);
                if (model.GetDeclaredSymbol(table) is not INamedTypeSymbol symbol || symbol.IsStatic)
                    continue;

                var attrs = symbol.GetAttributes();
                bool hasTable = attrs.Any(a =>
                    a.AttributeClass?.ToDisplayString() == TableAttributeFullName ||
                    a.AttributeClass?.ToDisplayString() == FlagTableAttributeFullName);
                if (!hasTable)
                    continue;

                refs.Add(new TableRef(symbol.Name, GetNamespace(symbol)));
            }

            if (refs.Count == 0)
                return;

            string contextNs = $"Socigy.OpenSource.DB.{db}.Context";
            string extensionsNs = $"Socigy.OpenSource.DB.{db}.Extensions";

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#pragma warning disable");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Data.Common;");
            sb.AppendLine("using System.Linq.Expressions;");
            sb.AppendLine("using System.Threading;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using Socigy.OpenSource.DB.Core;");
            sb.AppendLine("using Socigy.OpenSource.DB.Core.Context;");
            sb.AppendLine("using Socigy.OpenSource.DB.Core.Diagnostics;");
            sb.AppendLine();
            sb.AppendLine($"namespace {contextNs}");
            sb.AppendLine("{");

            EmitContextInterface(sb, db, refs);
            EmitContextImplementation(sb, db, refs);
            foreach (var t in refs)
            {
                EmitSetInterface(sb, t);
                EmitSetImplementation(sb, t);
            }
            EmitFactory(sb, db);

            sb.AppendLine("}");
            sb.AppendLine();

            EmitDiExtension(sb, db, contextNs, extensionsNs);

            ctx.AddSource($"{db}Context.g.cs", sb.ToString());
        }

        private static void EmitContextInterface(StringBuilder sb, string db, List<TableRef> refs)
        {
            sb.AppendLine($"    /// <summary>Testable facade over the {db} database. Resolve <c>ISocigyDatabaseFactory&lt;I{db}&gt;</c> and use ExecuteAsync/ExecuteTransactionAsync.</summary>");
            sb.AppendLine($"    public interface I{db}");
            sb.AppendLine("    {");
            foreach (var t in refs)
                sb.AppendLine($"        I{t.ClassName}Set {Pluralize(t.ClassName)} {{ get; }}");
            sb.AppendLine("        /// <summary>Runs <paramref name=\"work\"/> with the scope's connection — escape hatch for stored procedures or raw ADO.</summary>");
            sb.AppendLine("        Task<TResult> WithConnectionAsync<TResult>(Func<DbConnection, Task<TResult>> work);");
            sb.AppendLine("        /// <summary>Runs <paramref name=\"work\"/> with the scope's connection — escape hatch for stored procedures or raw ADO.</summary>");
            sb.AppendLine("        Task WithConnectionAsync(Func<DbConnection, Task> work);");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        private static void EmitContextImplementation(StringBuilder sb, string db, List<TableRef> refs)
        {
            sb.AppendLine($"    internal sealed class {db}Context : I{db}");
            sb.AppendLine("    {");
            sb.AppendLine("        private readonly SocigyDbScope _scope;");
            sb.AppendLine($"        public {db}Context(SocigyDbScope scope) {{ _scope = scope; }}");
            foreach (var t in refs)
                sb.AppendLine($"        public I{t.ClassName}Set {Pluralize(t.ClassName)} => new {t.ClassName}Set(_scope);");
            sb.AppendLine();
            sb.AppendLine("        public async Task<TResult> WithConnectionAsync<TResult>(Func<DbConnection, Task<TResult>> work)");
            sb.AppendLine("        {");
            sb.AppendLine("            var __acq = await _scope.AcquireAsync();");
            sb.AppendLine("            try { return await work(__acq.Connection); }");
            sb.AppendLine("            finally { await _scope.ReleaseAsync(__acq.Connection, __acq.OwnedByOperation); }");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public async Task WithConnectionAsync(Func<DbConnection, Task> work)");
            sb.AppendLine("        {");
            sb.AppendLine("            var __acq = await _scope.AcquireAsync();");
            sb.AppendLine("            try { await work(__acq.Connection); }");
            sb.AppendLine("            finally { await _scope.ReleaseAsync(__acq.Connection, __acq.OwnedByOperation); }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        private static void EmitSetInterface(StringBuilder sb, TableRef t)
        {
            string e = "global::" + t.FullName;
            string pred = $"Expression<Func<{e}, bool>>";
            sb.AppendLine($"    /// <summary>Mockable data-access seam for <c>{t.ClassName}</c>.</summary>");
            sb.AppendLine($"    public interface I{t.ClassName}Set");
            sb.AppendLine("    {");
            sb.AppendLine($"        Task<bool> ExistsAsync({pred} predicate);");
            sb.AppendLine($"        Task<{e}?> FirstOrDefaultAsync({pred} predicate);");
            sb.AppendLine($"        Task<List<{e}>> ToListAsync({pred}? predicate = null);");
            sb.AppendLine($"        Task<long> CountAsync({pred}? predicate = null);");
            sb.AppendLine($"        /// <summary>Inserts one entity. Pass <c>includeAutoFields: true</c> to also write auto-increment columns (supply your own values).</summary>");
            sb.AppendLine($"        Task<bool> InsertAsync({e} entity, bool includeAutoFields = false);");
            sb.AppendLine($"        /// <summary>Inserts many entities as batched multi-row INSERTs. Pass <c>includeAutoFields: true</c> to also write auto-increment columns. Returns the total rows inserted.</summary>");
            sb.AppendLine($"        Task<int> InsertMultipleAsync(IEnumerable<{e}> entities, bool includeAutoFields = false, CancellationToken cancellationToken = default);");
            sb.AppendLine($"        Task<int> UpdateAsync({e} entity);");
            sb.AppendLine($"        Task<int> DeleteAsync({pred} predicate);");
            sb.AppendLine($"        Task ForEachAsync({pred}? predicate, Func<{e}, Task> onRow, CancellationToken cancellationToken = default);");
            sb.AppendLine($"        /// <summary>Streams matching rows, projects each through <paramref name=\"onRow\"/>, and returns the projected results (materialized within the scope).</summary>");
            sb.AppendLine($"        Task<List<TResult>> ForEachAsync<TResult>({pred}? predicate, Func<{e}, Task<TResult>> onRow, CancellationToken cancellationToken = default);");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        private static void EmitSetImplementation(StringBuilder sb, TableRef t)
        {
            string e = "global::" + t.FullName;
            string pred = $"Expression<Func<{e}, bool>>";

            sb.AppendLine($"    internal sealed class {t.ClassName}Set : I{t.ClassName}Set");
            sb.AppendLine("    {");
            sb.AppendLine("        private readonly SocigyDbScope _scope;");
            sb.AppendLine($"        public {t.ClassName}Set(SocigyDbScope scope) {{ _scope = scope; }}");
            sb.AppendLine();

            // ToListAsync
            sb.AppendLine($"        public async Task<List<{e}>> ToListAsync({pred}? predicate = null)");
            sb.AppendLine("        {");
            sb.AppendLine("            var __acq = await _scope.AcquireAsync();");
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            sb.AppendLine($"                var __q = predicate == null ? {e}.Query() : {e}.Query(predicate);");
            EmitEnlist(sb, "__q");
            sb.AppendLine($"                var __list = new List<{e}>();");
            sb.AppendLine("                await foreach (var __row in __q.ExecuteAsync()) __list.Add(__row);");
            sb.AppendLine("                return __list;");
            sb.AppendLine("            }");
            sb.AppendLine("            finally { await _scope.ReleaseAsync(__acq.Connection, __acq.OwnedByOperation); }");
            sb.AppendLine("        }");
            sb.AppendLine();

            // FirstOrDefaultAsync
            sb.AppendLine($"        public async Task<{e}?> FirstOrDefaultAsync({pred} predicate)");
            sb.AppendLine("        {");
            sb.AppendLine("            var __acq = await _scope.AcquireAsync();");
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            sb.AppendLine($"                var __q = {e}.Query(predicate).Limit(1);");
            EmitEnlist(sb, "__q");
            sb.AppendLine("                await foreach (var __row in __q.ExecuteAsync()) return __row;");
            sb.AppendLine("                return null;");
            sb.AppendLine("            }");
            sb.AppendLine("            finally { await _scope.ReleaseAsync(__acq.Connection, __acq.OwnedByOperation); }");
            sb.AppendLine("        }");
            sb.AppendLine();

            // ExistsAsync
            sb.AppendLine($"        public async Task<bool> ExistsAsync({pred} predicate)");
            sb.AppendLine("            => await FirstOrDefaultAsync(predicate) != null;");
            sb.AppendLine();

            // CountAsync (v1: drain-count)
            sb.AppendLine($"        public async Task<long> CountAsync({pred}? predicate = null)");
            sb.AppendLine("        {");
            sb.AppendLine("            var __acq = await _scope.AcquireAsync();");
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            sb.AppendLine($"                var __q = predicate == null ? {e}.Query() : {e}.Query(predicate);");
            EmitEnlist(sb, "__q");
            sb.AppendLine("                long __count = 0;");
            sb.AppendLine("                await foreach (var __row in __q.ExecuteAsync()) __count++;");
            sb.AppendLine("                return __count;");
            sb.AppendLine("            }");
            sb.AppendLine("            finally { await _scope.ReleaseAsync(__acq.Connection, __acq.OwnedByOperation); }");
            sb.AppendLine("        }");
            sb.AppendLine();

            // InsertAsync
            sb.AppendLine($"        public async Task<bool> InsertAsync({e} entity, bool includeAutoFields = false)");
            sb.AppendLine("        {");
            sb.AppendLine("            var __acq = await _scope.AcquireAsync();");
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            sb.AppendLine("                var __b = entity.Insert();");
            sb.AppendLine("                if (includeAutoFields) __b.WithAllFields();");
            EmitEnlist(sb, "__b");
            sb.AppendLine("                return await __b.ExecuteAsync();");
            sb.AppendLine("            }");
            sb.AppendLine("            finally { await _scope.ReleaseAsync(__acq.Connection, __acq.OwnedByOperation); }");
            sb.AppendLine("        }");
            sb.AppendLine();

            // InsertMultipleAsync (batched multi-row INSERT)
            sb.AppendLine($"        public async Task<int> InsertMultipleAsync(IEnumerable<{e}> entities, bool includeAutoFields = false, CancellationToken cancellationToken = default)");
            sb.AppendLine("        {");
            sb.AppendLine("            var __acq = await _scope.AcquireAsync();");
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            sb.AppendLine("                var __tx = _scope.HasAmbientTransaction ? _scope.AmbientTransaction : null;");
            sb.AppendLine($"                return await {e}.InsertMultipleAsync(entities, __acq.Connection, __tx, includeAutoFields, cancellationToken);");
            sb.AppendLine("            }");
            sb.AppendLine("            finally { await _scope.ReleaseAsync(__acq.Connection, __acq.OwnedByOperation); }");
            sb.AppendLine("        }");
            sb.AppendLine();

            // UpdateAsync
            sb.AppendLine($"        public async Task<int> UpdateAsync({e} entity)");
            sb.AppendLine("        {");
            sb.AppendLine("            var __acq = await _scope.AcquireAsync();");
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            sb.AppendLine("                var __b = entity.Update().WithAllFields();");
            EmitEnlist(sb, "__b");
            sb.AppendLine("                return await __b.ExecuteAsync();");
            sb.AppendLine("            }");
            sb.AppendLine("            finally { await _scope.ReleaseAsync(__acq.Connection, __acq.OwnedByOperation); }");
            sb.AppendLine("        }");
            sb.AppendLine();

            // DeleteAsync
            sb.AppendLine($"        public async Task<int> DeleteAsync({pred} predicate)");
            sb.AppendLine("        {");
            sb.AppendLine("            var __acq = await _scope.AcquireAsync();");
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            sb.AppendLine($"                var __b = {e}.DeleteNonInstance().Where(predicate);");
            EmitEnlist(sb, "__b");
            sb.AppendLine("                return await __b.ExecuteAsync();");
            sb.AppendLine("            }");
            sb.AppendLine("            finally { await _scope.ReleaseAsync(__acq.Connection, __acq.OwnedByOperation); }");
            sb.AppendLine("        }");
            sb.AppendLine();

            // ForEachAsync (streaming; busy-guarded)
            sb.AppendLine($"        public async Task ForEachAsync({pred}? predicate, Func<{e}, Task> onRow, CancellationToken cancellationToken = default)");
            sb.AppendLine("        {");
            sb.AppendLine("            var __conn = await _scope.BeginStreamAsync(cancellationToken);");
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            sb.AppendLine($"                var __q = predicate == null ? {e}.Query() : {e}.Query(predicate);");
            sb.AppendLine("                if (_scope.HasAmbientTransaction) __q.WithTransaction(_scope.AmbientTransaction!); else __q.WithConnection(__conn);");
            sb.AppendLine("                __q.WithDiagnostics(_scope.Diagnostics);");
            sb.AppendLine("                await foreach (var __row in __q.ExecuteAsync())");
            sb.AppendLine("                {");
            sb.AppendLine("                    cancellationToken.ThrowIfCancellationRequested();");
            sb.AppendLine("                    await onRow(__row);");
            sb.AppendLine("                }");
            sb.AppendLine("            }");
            sb.AppendLine("            finally { _scope.EndStream(); }");
            sb.AppendLine("        }");
            sb.AppendLine();

            // ForEachAsync<TResult> — projects each streamed row and returns the results (materialized in-scope,
            // so nothing lazy escapes the open connection).
            sb.AppendLine($"        public async Task<List<TResult>> ForEachAsync<TResult>({pred}? predicate, Func<{e}, Task<TResult>> onRow, CancellationToken cancellationToken = default)");
            sb.AppendLine("        {");
            sb.AppendLine("            var __conn = await _scope.BeginStreamAsync(cancellationToken);");
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            sb.AppendLine($"                var __q = predicate == null ? {e}.Query() : {e}.Query(predicate);");
            sb.AppendLine("                if (_scope.HasAmbientTransaction) __q.WithTransaction(_scope.AmbientTransaction!); else __q.WithConnection(__conn);");
            sb.AppendLine("                __q.WithDiagnostics(_scope.Diagnostics);");
            sb.AppendLine("                var __results = new List<TResult>();");
            sb.AppendLine("                await foreach (var __row in __q.ExecuteAsync())");
            sb.AppendLine("                {");
            sb.AppendLine("                    cancellationToken.ThrowIfCancellationRequested();");
            sb.AppendLine("                    __results.Add(await onRow(__row));");
            sb.AppendLine("                }");
            sb.AppendLine("                return __results;");
            sb.AppendLine("            }");
            sb.AppendLine("            finally { _scope.EndStream(); }");
            sb.AppendLine("        }");

            sb.AppendLine("    }");
            sb.AppendLine();
        }

        private static void EmitEnlist(StringBuilder sb, string builderVar)
        {
            sb.AppendLine($"                if (_scope.HasAmbientTransaction) {builderVar}.WithTransaction(_scope.AmbientTransaction!); else {builderVar}.WithConnection(__acq.Connection);");
            sb.AppendLine($"                {builderVar}.WithDiagnostics(_scope.Diagnostics);");
        }

        private static void EmitFactory(StringBuilder sb, string db)
        {
            sb.AppendLine($"    /// <summary>The DI-resolvable factory for the {db} database context.</summary>");
            sb.AppendLine($"    public sealed class {db}Factory : SocigyDatabaseFactoryBase<I{db}>");
            sb.AppendLine("    {");
            sb.AppendLine($"        public {db}Factory(IDbConnectionFactory connections, SocigyDbContextOptions options = null, DbDiagnosticsContext diagnostics = null)");
            sb.AppendLine("            : base(connections, options, diagnostics) { }");
            sb.AppendLine($"        protected override I{db} CreateContext(SocigyDbScope scope) => new {db}Context(scope);");
            sb.AppendLine("    }");
        }

        private static void EmitDiExtension(StringBuilder sb, string db, string contextNs, string extensionsNs)
        {
            sb.AppendLine($"namespace {extensionsNs}");
            sb.AppendLine("{");
            sb.AppendLine("    using Microsoft.Extensions.DependencyInjection;");
            sb.AppendLine("    using Microsoft.Extensions.DependencyInjection.Extensions;");
            sb.AppendLine("    using Microsoft.Extensions.Logging;");
            sb.AppendLine("    using Socigy.OpenSource.DB.Core;");
            sb.AppendLine("    using Socigy.OpenSource.DB.Core.Context;");
            sb.AppendLine("    using Socigy.OpenSource.DB.Core.Diagnostics;");
            sb.AppendLine($"    using {contextNs};");
            sb.AppendLine();
            sb.AppendLine($"    public static class {db}ContextExtensions");
            sb.AppendLine("    {");
            sb.AppendLine($"        /// <summary>Registers <c>ISocigyDatabaseFactory&lt;I{db}&gt;</c>. Call after <c>Add{db}()</c> which registers the connection factory.</summary>");
            sb.AppendLine($"        public static IServiceCollection Add{db}Context(this IServiceCollection services, Action<SocigyDbContextOptions> configure = null)");
            sb.AppendLine("        {");
            sb.AppendLine("            var __options = new SocigyDbContextOptions();");
            sb.AppendLine("            configure?.Invoke(__options);");
            sb.AppendLine("            services.TryAddSingleton(__options);");
            sb.AppendLine($"            services.AddSingleton<ISocigyDatabaseFactory<I{db}>>(sp =>");
            sb.AppendLine($"                new {contextNs}.{db}Factory(");
            sb.AppendLine($"                    sp.GetRequiredKeyedService<IDbConnectionFactory>(\"{db}\"),");
            sb.AppendLine("                    sp.GetService<SocigyDbContextOptions>() ?? new SocigyDbContextOptions(),");
            sb.AppendLine("                    new DbDiagnosticsContext(sp.GetService<ILoggerFactory>(), sp.GetService<SocigyDbDiagnosticsOptions>())));");
            sb.AppendLine("            return services;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
        }

        private static string GetNamespace(INamedTypeSymbol symbol)
        {
            var parts = new Stack<string>();
            var ns = symbol.ContainingNamespace;
            while (ns != null && !string.IsNullOrEmpty(ns.Name))
            {
                parts.Push(ns.Name);
                ns = ns.ContainingNamespace;
            }
            return string.Join(".", parts);
        }

        private static string Pluralize(string name)
        {
            if (string.IsNullOrEmpty(name)) return name + "Set";
            char last = char.ToLowerInvariant(name[name.Length - 1]);
            if (name.EndsWith("s") || name.EndsWith("x") || name.EndsWith("z") ||
                name.EndsWith("ch") || name.EndsWith("sh"))
                return name + "es";
            if (last == 'y' && name.Length > 1 && !IsVowel(name[name.Length - 2]))
                return name.Substring(0, name.Length - 1) + "ies";
            return name + "s";
        }

        private static bool IsVowel(char c)
        {
            c = char.ToLowerInvariant(c);
            return c == 'a' || c == 'e' || c == 'i' || c == 'o' || c == 'u';
        }
    }
}
